Slimefun/Slimefun4

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/NuclearReactor.java

Fixes the possibility of the energy network crashing and the energy regulator disappearing.  This could have been caused by a Null pointer Exception on previous line 291 (now 294), where the BlockStorage checks for the stored "reactor-mode", when if the mode was never changed it would not have been set at all.

Fixes Reactor Crash

---

src/me/mrCookieSlime/Slimefun/SlimefunStartup.java

allows the Bukkit version: PluginBukkitBridge so this can load on the Rainbow server mod

Allows SlimeFun to load on the BukkitBridge for the Rainbow server mod

---

src/me/mrCookieSlime/Slimefun/listeners/BowListener.java

Since ProjectileHitEvent is delayed, we check to make sure the arrow is still a valid entity before calling handleGrapplingHook. Otherwise, it gets called twice and the Grappling Hook gets duplicated.
Also fix some instances of the Grappling Hook's arrow and leash not being removed.

Fix Grappling Hooks duplicating

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Mostly, For some reason I think it's better for it to give out 4 Coal, rather than just two from the else statement, because other ores, like Coal is really needed, and if so, People would never opt-in for an advanced one, if instead you could use the normal one, and a fortune pick.

Coal Ore is more reasonable to give 4 coal, rather than two in Advanced Digi-Miner

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectrifiedCrucible.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
src/me/mrCookieSlime/Slimefun/listeners/BackpackListener.java

Fixes:
- Backpacks getting stuck in backpacks with number keys.
- Putting shulker boxes inside backpacks for infinite storage.
- A dupe where a player would drop the backpack at the same time as opening it.
- Crucible not making lava in return for hardened_clay

Backpack & crucible fixes

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Adds unplacable-blocks option to BlockPlacer. 
**Example situation where this is needed:**
McMMO detects blocks placed by Slimefun to be natural blocks and gives xp for it, admins will be able to prevent ores from being placed. Thus, preventing McMMO xp dupe.

Added unplaceable-blocks for BlockPlacer

---

src/me/mrCookieSlime/Slimefun/SlimefunGuide.java

A tiny addition to provide a better user experience : don't have to search in the whole guide to find the wiki link for an item you saw in the display recipes.

Show the item display page when clicking on it in a machine's display recipes

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Water Ancient Rune is more expensive than the 3 other runes, and we obtain less than them... This is inconsistent.

Crafting a Water Ancient Rune now gives 4 instead of 2

---

src/me/mrCookieSlime/Slimefun/api/item_transport/CargoNet.java

Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/408
Was due to the JSON storage format (everything is String). #getInt was therefore returning 0.

Fixes ignored frequencies for Cargo

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
src/me/mrCookieSlime/Slimefun/holograms/InfusedHopper.java

This fixes a bug that led to abandoned ArmorStands (what I was referring
to when I said "target") that lingered after the hopper was destroyed.
The issue was that tick (called asynchronously) was creating a new
ArmorStand (via InfusedHopper.getArmorStand()) after the block handler's
onBreak call removed the one that was created in onPlace.
The code that recreates the ArmorStand remains in tick() just in case,
somehow, it ends up getting removed by some other force. However, this
code should never be reached if the hopper itself is removed.
This fixes TheBusyBiscuit/Slimefun4#189,
fixes TheBusyBiscuit/Slimefun4#190, and
fixes TheBusyBiscuit/Slimefun4#428.

Only create a hopper "target" as long as the block is actually a hopper.

---

src/me/mrCookieSlime/Slimefun/api/BlockStorage.java
src/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java
src/me/mrCookieSlime/Slimefun/api/inventory/UniversalBlockMenu.java

CraftBukket's HumanEntity.closeInventory() apparently removes the human
from the inventory's viewer list, resulting in an exception when we were
calling closeInventory while iterating over the list of said viewers.
Fixes TheBusyBiscuit/Slimefun4#364.

Fix ConcurrentModificationException that occurred when reactor explodes.

---

pom.xml
src/plugin.yml

This will also specify the version in the name of the file on build, which is a lot more practical :)
I made this little fix due to inconsistencies between plugin.yml and pom.xml version, which gave me a bit of trouble when importing Slimefun in a Maven project.

Use ${project.version} from pom.xml in plugin.yml

---

src/me/mrCookieSlime/Slimefun/Commands/SlimefunCommand.java
src/me/mrCookieSlime/Slimefun/Setup/Messages.java
src/plugin.yml

From the suggestion of @oddare (https://github.com/TheBusyBiscuit/Slimefun4/issues/491), I've added the command to open the Slimefun Guide just typing "/sf open_guide". I also added the tab completion "open_guide" and a description of it.

Opening the SF guide with commands #491

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Ore washer has a bug, which lets players dupe certain kind of dust. So, I created a tiny fix, which'll remove this dupe.
Let's, for example, dupe Copper Dust. For this, we have to fill the Dispencer of Ore Washer in this way:
Where:
While clicking Ore Washer, we will get messages about overflow of Dispenser's inventory, but, with some probablity, our machine'll generate us a Copper Dust.
It work with any kind of Dusts.
**Why it works:**
CSCoreLib's method InvUtils.fits() returns true even when there're no free slots in the inventory.
So, I replaced it with a check for a free slot. (inv.firstEmpty() returns -1 only if inventory have no free slots)

Ore washer dupe fix

---

src/me/mrCookieSlime/Slimefun/GitHub/Contributor.java
src/me/mrCookieSlime/Slimefun/GitHub/GitHubSetup.java
src/me/mrCookieSlime/Slimefun/SlimefunGuide.java

Documented and privatized fields in Contributor object
Improved Credits display by showing the head of the contributor (if his MC's nickname is the same than on GitHub) and showing contributions in a more understandable way (just a percentage was not really "helpful")
Added Starts count in Settings panel
I put `@since 4.2.0` in the javadocs, because I want the next version to be a big update, with, at least, the item hashing and a localization system.

Improved Settings & Contributors panels

---

src/me/mrCookieSlime/Slimefun/listeners/BackpackListener.java

Way to reproduce bug:
1. Open the Cooler and try to move any Juice inside of it (Do not press Shift!)
2. When you'll click empty slot with Juice at cursor, Cooler will cancel click
This bug exist because clicking at empty slot isn't handled properly - when we click at empty slot, .getCurrentItem() returns us not _null_ but an ItemStack with type "Air". Probably, this behavour was added in new versions of Bukkit API

Fixed Cooler rejecting Juices

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Resolves: https://github.com/TheBusyBiscuit/Slimefun4/issues/466
There has been a long standing issue where Reinforced Spawners always place as a Pig Spawner as of the last few months due to the block state changes that occurred in Bukkit / Craftbukkit / Spigot a few months ago.
This pull request fixes that by properly referencing the variable "spawner" of the craftblock state, which properly applies the modified data (being the set type) and updates that modified data onto the block.
This fix was tested on MC 1.12.2 but it should work for all earlier versions too.
This fix is similar to the changes that made furnaces properly have their data set here: https://github.com/TheBusyBiscuit/Slimefun4/pull/567

Fix Reinforced Spawners being a Pig Spawner when placed.

---

src/me/mrCookieSlime/Slimefun/listeners/BlockListener.java

1) Stop falling blocks from falling into a spot where an SF machine was just mined. Typically the blockstorage does not update fast enough, causing machine duplication. The event is cancelled, and the falling entities drop as items instead of disappearing.
2) Nearly the same as above, but with pistons pushing solid blocks into air blocks which had a slimefun machine in it a moment prior. Typically the blockstorage does not update fast enough, causing machine duplication.

Fix discrepancies between block storage data and server events

---

src/me/mrCookieSlime/Slimefun/api/Soul.java

Fixed  #579 
Now Soulbound items will be retrieved only if any other plugin hadn't returned them already

 Fixed incompatibility with KeepItems-like plugins

---

src/me/mrCookieSlime/Slimefun/listeners/DamageListener.java

Related to #239 - by finding a mob that can pickup loot and giving them heads (so, a lot of slimefun items), armour and an item they can pick up there is a chance to dupe those items. For heads in particular, you can drop a stack of heads which will then dupe to two stacks, so it is a particularly bad dupe bug. 
This 'fix' just prevents it from applying to those mobs, which slightly nerfs the talisman for Skeletons, Wither Skeletons and Zombies. I cannot find a good way to tell the probability of the mobs being able to pick up items otherwise you could adjust the percentages, but this fix resolves the duplication bug as a priority.

Prevent Talisman of the Hunter from duping armour/heads

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java
src/me/mrCookieSlime/Slimefun/api/energy/EnergyNet.java

The issue is as follows:
When certain AReactors (Nuclear) produces energy it stores it in its own chargeable state.
The current charge is returned from this function. ([Line 303](https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java#L303))
However, in the energy net code, it then takes this value and adds on any storage that the block has:
https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/api/energy/EnergyNet.java#L116-L119
Which means the the Nuclear Reactors currently produce twice their described power and when the energy network is full, they produce the equivalent of their storage every tick (So 16kJ) which makes them incredibly OP and broken. This just returns zero …

Fix AReactor Issue

---

src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AFarm.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AdvancedCargoOutputNode.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AnimalGrowthAccelerator.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutoBreeder.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutomatedCraftingChamber.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CargoCraftingNode.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CargoInputNode.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CropGrowthAccelerator.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricSmeltery.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ReactorAccessPort.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/WitherAssembler.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/XPCollector.java

I updated every onBreak() handler I could find that included a call to dropItemNaturally(). The updated code will remove the item from the device's inventory immediately after it is dropped using replaceExistingItem(). The only device I didn't update was the ANCIENT_PEDESTAL. It did not appear to use the inventory setup the other devices used so I wasn't sure how to handle it. I don't think all the items I updated were actually vulnerable to the duplication bug. I have a feeling it was limited to the onBreak() handlers which used a for loop to cycle through all the inventory slots. But I also think consistency is correct. I also tested using inv.close() at the start of the onBreak() and it does appear to correct the bug as well. I chose not to use this solution as there could exist some …

Fix Two Player Device Inventory Item Duplication Bug

---

src/config.yml
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricDustWasher.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
src/me/mrCookieSlime/Slimefun/SlimefunStartup.java

When the Slimefun plugin was updated on the server I play on, many players were less than pleased with the new behavior of the ore washer. They liked being able to force the ore washer to produce specific dust types. In addition, the server I play on has cargo networks disabled, so the new behavior of the electric dust washer makes them all but unusable. This PR adds two configuration options: legacy_ore_washer and legacy_dust_washer. They default to false which will maintain the current, updated behavior of each device. If an option is changed to true, then the associated device will revert to the old style behavior.

Allow admins to chose ore washer and dust washer behavior

---

src/me/mrCookieSlime/Slimefun/api/BlockInfoConfig.java
src/me/mrCookieSlime/Slimefun/api/BlockStorage.java

As the screenshot shows,
```java
new Config("data-storage/Slimefun/temp.yml")
```
is particularly expensive because it has to try to load a file from disk.
This PR will avoid that call for block info and also save time spent parsing JSON.
Block info has always been limited to Map<String, String> despite the Config interface, so this won't change anything there. Mutating the Config will change the block info now, but I doubt that happens anywhere without the block info being set anyway. If it's a problem, the Map can of course be cloned.

Parse block info at startup

---

src/me/mrCookieSlime/Slimefun/listeners/AndroidKillingListener.java

Since 1.11, Wither Skeletons have their own ID; this change hasn't been reflected in code since.
This pull request fixes that.

Fixes Butcher Androids being able to loot Wither Skeleton Skulls again.

---

src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java

- Title says it. Just implemented vanilla behavior, so you can eat/place blocks/etc while sneaking with an item.
- I didn't have any problems with it but now potions are removed one tick faster than before. Just in case...
- As 0 actually means the next tick.

Prevent opening inventory while sneaking with an item

---

src/me/mrCookieSlime/Slimefun/SlimefunGuide.java

- Cheat mode (command & book) now does not reset guide history.
- You can cheat items but still be able to watch the needed recipe. Very useful for testing purposes.
- Replaced deprecated code in the same class.

 Don't reset guide history when using cheat mode

---

src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/FoodComposter.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/FoodFabricator.java
src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

- Using full names instead of numbers according to 1.13 standard as those are different items and not improved ones *(like CROP_GROWTH_ACCELERATOR and CROP_GROWTH_ACCELERATOR_2)*.
- Not really necessary but I had some problems recognizing them :P

Rename ORGANIC_FOOD and FERTILIZER

---

src/me/mrCookieSlime/Slimefun/api/BlockStorage.java

Slimefun has a known issue where blocks get corrupted after a restart. Blocks look like Slimefun items but they don't work and when broken turn out to be `CSCoreLib's Head`.
The main cause for this issue turns out to be that as Slimefun loads its block configuration from each `.sfb` file in `stored-blocks/%world%` when it starts up, it encounters a `null.sfb` file with invalid data, overwriting an otherwise vaid block and corrupting it.
On a server with issues, there'll be a `null.sfb` file in `data-storage/Slimefun/stored-blocks/[world]/` with contents similiar to this:
```
world;1710;63;-3792: '{"energy-charge":"0"}'
world;1704;63;-3796: '{"energy-charge":"0"}'
world;1707;63;-3798: '{"energy-charge":"0"}'
world;1704;63;-3795: '{"energy-charge":"0"}'
world;1707;63;-3792: …
```

Prevent Slimefun blocks from getting corrupted at startup

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/EnhancedFurnace.java

Return efficiency when getFuelEfficiency is called instead of speed.

Return efficiency when getFuelEfficiency is called

---

src/me/mrCookieSlime/Slimefun/Lists/RecipeType.java

* Specifying the type in the diamond operator is not necessary from java 7.
* Spelling mistake: convertable -> convertible.
* Encapsulated the item & machine variables.
* Changed the constructor as Slimefunitem item is not used anywhere except in the constructor.

Minor codecleanup & fixed spelling mistake

---

src/me/mrCookieSlime/Slimefun/holograms/Projector.java

Method setCustomName removes unnecesary ChatColor codes (e.g. &r that doesn't reset anything). Saving the real CustomName to BlockStorage resolves the issue.

Fix for #915

---

src/me/mrCookieSlime/Slimefun/SlimefunGuide.java

For generators and reactors we show the fuels underneath the schematics or build instructions:
When there are more fuels than available space to show them, we'll overflow, causing the custom inventory to not work and Slimefun (or well, CSCoreLib, but caused by Slimefun) throwing exceptions:
`IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots`
This issue currently occurs with the Bio Reactor. Reproducing it is easy:
1. Open the SF guide - `/sf guide`
2. Click `Energy and Electricity`
3. Click `Bio Reactor`
4. At this point the aforementioned Exception is logged to the console and the player is simply handed the Bio Reactor which they can place and use (Note: Once they do that, the Slimefun guide can't be used until they reconnect)
There was …

Fix for guide bug when building Bio Reactor (and maybe others)

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

As discussed on Discord, the Explosive Pickaxe currently doesn't take any damage and therefore doesn't lose durability, which isn't a desirable behavior for some of us.
This commit adds a 'damage-on-use' item setting (in `plugins/Slimefun/items.yml`) for EXPLOSIVE_PICKAXE, which is disabled by default, but can be enabled like this:
```
EXPLOSIVE_PICKAXE:
enabled: true
...
damage-on-use: true
```
When enabled, the Explosive Pickaxe will get damaged for each block it breaks, in the same way a normal Diamond Pickaxe would get damage if it were to break those blocks. This seems to be similar to how Slimefun damages other tools.
Players can still enable Unbreaking (e.g. durability) on the pickaxe through enchants.

Damage explosive pickaxe on use (configurable, off by default)

---

src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java

When a Slimefun item that doesn't have a BlockHandler is broken by a tool that does have a BlockHandler and that tool's BlockHandler returns true, Slimefun would stop handling the "onBlockBreak" event and would not drop the Slimefun item that was broken but some vanilla block instead.
I'm aware that this is not the easiest to understand, so here's a little explanation that might help: 
Scenario:
* An **Enhanced Furnace X** is broken by a **Pickaxe of Vein Mining**,
* The **Enhanced Furnace X** doesn't have any block or block break handlers (trust me, it doesn't).
* The **Pickaxe of Vein Mining** [has a BlockBreakHandler](https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L2461) which basically returns `true` every time you break …

Drop Slimefun items when broken by another Slimefun tool

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

The reason for this is because it has created a duplication glitch with the explosive pickaxe. 
*NOTE*
I checked past commits and it seems that nothing has been reverted as far as I can tell. Also apologies for the material mix-up. I was testing it on 1.13 at the time and I know for sure it will work for 1.14

Switch boolean allow = true; to false

---

src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java

1. Added the event for grindstone inventory click to prevent grindstoning any Slimefun Items, including books, (except legacy), #953
2. Added the Slimefun books into blacklist for Anvil, to prevent renaming the books which can be grindstoned without getting filtered.
EDIT:
Uses InventoryType.GRINDSTONE to check. Might break those under 1.14??? Needs testing.

Fix for #953, add Slimefun books to anvil and grindstone blacklist.

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Added sandstone and red sandstone to grindstone.
1 (red) sandstone --> 4 (red) sand
Idea came from Jareth Maxter#4344
> Add Sandstone to Sand option for Grindstone - gives people a reason to pickaxe down a desert and increase the sand resource on servers
This suggestion were upvoted 5:0 suggesting that it's a desired feature by the community. 
NOTE: Due to the limitation of the sf guide, the red sandstone recipe doesn't fit in the /sf guide view.
It works, but just isn't visually shown. For this recipe, it doesn't really matter due to red sandstone simply being a variation of sandstone, and you could argue that they don't need 2 seperate recipe slots. The user can simply experiment and find that the red sandstone works just as well.
Maybe modifying the sf guide to be able to show several …

Add sandstone to grind stone

---

src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java
src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

**Description**
Added copper wire, a crafting component made from copper ingots.
3 copper ingots --> 8 copper wires
This pull request changes the recipe of electric motor and heating coil to use this component instead.
Instead of using 6 and 8 ingots in their recipe, they now use 6 and 8 copper wires, respectively.
Copper wire takes 15 levels to research, and is in the category TECH_MISC (Technical Components)
**Why?**
Slimefun is notorious for having draining copper reserves, more than any other dust. This change aims to rebalance dust usage a bit. Copper will still be a highly sought-after dust, but not as extremely unbalanced.
**What's next?**
By not making copper the bottleneck to literally everything, this paves way for other dusts to be used in recipes. It doesn't make sense that …

Add copper wire

---

src/config.yml
src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunMachine.java
src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Most of the code is commented, but here is the short version:
For all basic machines that incorporate dispensers in their design, they will support output chests.
The output chest is a chest made with 5 lead ingots, 1 hopper and 1 chest, and takes 20 levels to research. When placed adjacent (up, down, north, south, east, west) to the dispensers, the output chest will take the priority over the standard dispenser inventory as an output inventory for products.
The main idea behind the code is the new static method findValidOutputInv(ItemStack product, Block dispBlock, Inventory dispInv) that replaces the old functionality of using InvUtils.fit(). 
The method allows for an output chest but has a fallback to using the old dispenser inventory as output.
Most of the changes take place in …

Add outputChest functionality

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

A)
Fixed spawner dupe.
Reproducing:
A) Pickaxe of Containment
B) Try to break a reinforced spawner
C) You will get a reinforced spawner and a broken spawner.
Fix:
Add the if-statement which basically boils down to if (BlockStorage.hasBlockInfo(b)) return true;
This will nullify the event. If the if-statement resolves to true then it will is not a vanilla spawner and
the containment pick should therefore not work.
The actual implementation is if (b.getType() != Material.SPAWNER || BlockStorage.hasBlockInfo(b)) return true; and is just a way to bake in the relatively simple boolean into a similar check.
B)
Added some quick refactoring, so instead of doing,
foo(e.getBlock);
you now do,
Block b = e.getBlock();
such that the call is foo(b);

Fix spawner dupe and objectified e.getBock()

---

src/me/mrCookieSlime/Slimefun/listeners/DamageListener.java

Removes the duplication of items when killing ChestedHorse(Llamas, Donkey, etc.) with Talisman of the Hunter. Should fix #729.

Fixes ChestedHorse Duplication Bug

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ReactorAccessPort.java

Overhals The reactor and reactor port to be a bit more user friendly and useful.   
Currently there is no way to see the status of a reactor via the access port, this PR makes the reactor port a bit more useful as a remote tool.    
Once a reactor detects an attached Access Port clicking on the access port will show the GUI of the active reactor,giving the user the option to adjust the focus of the reactor as well as see remaining coolant.  
An information icon has been added to the Reactor's GUI which shows if an access port is connected or not with some info about how to connect one if none is found..   Provided a port is found the user can click on the icon to open the Access Port's gui if so desired,  OR they can shift click the access port to access it rather than the reactor's gui.

Reactor fix

---

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Addresses ItemDuplication Bug: 1003
https://github.com/TheBusyBiscuit/Slimefun4/issues/1003
This fix will stop the duplication glitch / console error, but will prevent Stripped_<type>_log from being used in the table saw, there is a fix submitted to MaterialHelper.java in CS-CoreLib that once accepted will allow Stripped_logs to work properly.     The MaterialHelper does detect Stripped log's as logs but it does not properly provide a wood type and returns Material.AIR rather than a NULL material which created the issue.

Table Saw Bug #1003 fix

---

src/me/mrCookieSlime/Slimefun/listeners/BackpackListener.java

Addresses issue #948 
Whenever a player right clicked an AIR block the backpack-already-open message would appear in chat however the backpack would still open...  Right clicking a block did not cause this message to appear.   Changed to event.getItem() rather than player.getInventory().getItemInMainHand();   Resolves the issue.

Backpack fix 948

---

src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java
src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
src/me/mrCookieSlime/Slimefun/listeners/BackpackListener.java
src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java

This PR does 2 things:
1. Add double-chest-sized backpack, named "Radiant Backpack". With 54 slots, it's the next in the series of normal backpacks, succeeding the gilded one. The recipe is the same, but with 24k gold instead of 22k and of course requiring a gilded pack instead of a woven one.
2. Change the recipe of the soulbound pack to require the radiant pack instead, since it's the highest tier of backpack now.
There is an extra commit that changed back indents... I don't know why but git messes it up somehow...

Add double-chest backpack (Radiant Backpack)

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricFurnace.java

fixes #894 - Electric Furnace
Original Issue, also mentioned table saw would not work, the Sawmill could not easily be fixed with the current slimefun design of the machine as it required placement of the log then activation of the machine.   The Sawmill was replaced with the TableSaw however it uses a 1.14 block so won't be helpful on a 1.13 server.

Fix electric furnaces not being able to use logs.

---

src/me/mrCookieSlime/Slimefun/Objects/MultiBlock.java
src/me/mrCookieSlime/Slimefun/listeners/BlockListener.java

I replaced the code checking for multiblocks
Removed the vast majority of the old Multiblock checking system and replaced it with a new recursive approach. I also changed some parts of the MultiBlock to fit the new code and also added support for the now deprecated old constructor which should prevent stuff from breaking without using the new constructor.
There is no open related issue, but this fixes the currently (as of 
307a439) broken Multiblocks. (Multiblock are not recognized anymore by the Code replaced here)
Addedum:
I did not find any code style regulations, so i just used the standart eclipse ones.

MultiBlockListener overhaul

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
src/me/mrCookieSlime/Slimefun/Setup/Messages.java
src/me/mrCookieSlime/Slimefun/SlimefunGuide.java

I decided that it would be better all around to be able to change the permission message per item rather than one global message.
Added permission-message string list
Removed tooltips.item-message in messages class

Changed item-permission message to be per item rather than one global list

---

src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java

Fixes ArrayIndexOutOfBounds exception in RainbowTicker#uniqueTick.
Fixed the wrong index defining.
#1098

Fixes #1098.

---

src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/StormStaff.java

Fixed cheated storm staff having unlimited usage also improve the way it is done, since it was going through all possible usages checking the lore on each one...
Downside: It will reset the usage on current items due to it being saved/loaded in a different way, this can be mitigated for now by doing a check if it had a key and then if not checking the lore and parsing it. Not sure how used this item is though to justify such a thing.
* The constant item now has MAX_USES in the lore
* Get the usage from the items NBT (or MAX_USES) and handle.
Resolves #1102

Improve storm staff usages

---

src/me/mrCookieSlime/Slimefun/Setup/CSCoreLibLoader.java
src/me/mrCookieSlime/Slimefun/SlimefunPlugin.java

Slimefun produces two NPEs when trying to load without CS-CoreLib:
1. https://pastebin.com/DvWTsNx8
2. https://pastebin.com/q8hxFX8z
Fixed those NPEs :P
Also replaces spaces with tabs as there was a mix of them.
N/A

Fix two NPEs when loading without CS-CoreLib

---

pom.xml
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunManager.java
src/me/mrCookieSlime/Slimefun/api/SlimefunItemStack.java
src/me/mrCookieSlime/Slimefun/utils/Constants.java

Adds the item ID under the sf_item tag.
In the SlimefunItem root constructors add the item ID. Some methods which previously went through the whole item to check now check for the ID first and if equal return there. This will improve performance on these lookups.
N/A
Eventually this entire plugin could not even have to rely on files. Everything could just be in NBT >:)
Would be good in terms of space and general data corruption.

Persistent data on items

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/BlockPlacer.java

Allow BlockPlacer to place blocks while retaining certain data of the block.
BlockPlacer will set block's name and inventory according to its itemstack after placing it.
Resolves #1164

Allow BlockPlacer to place blocks while retaining certain data

---

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/PickaxeOfTheSeeker.java

Fixed NullPointerException caused by Java evaluating:
```Java
if (p.getLocation().getBlock().getRelative(x, y, z).getType().toString().endsWith("_ORE") && closest == null || p.getLocation().distance(closest.getLocation()) < p.getLocation().distance(p.getLocation().getBlock().getRelative(x, y, z).getLocation()))
```
as
```Java
if ((p.getLocation().getBlock().getRelative(x, y, z).getType().toString().endsWith("_ORE") && closest == null) || p.getLocation().distance(closest.getLocation()) < p.getLocation().distance(p.getLocation().getBlock().getRelative(x, y, z).getLocation()))
```
causing the location distance check after the or operator to generate a NullPointerException because closest is null.
Added brackets to allow proper evaluation of the checks.
None

Fixed NullPointerException when using Pickaxe of the Seeker

---

src/me/mrCookieSlime/Slimefun/Objects/LockedCategory.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/EnhancedCraftingTable.java
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/MagicWorkbench.java
src/me/mrCookieSlime/Slimefun/Setup/SlimefunLocalization.java
src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
src/me/mrCookieSlime/Slimefun/api/PlayerProfile.java
src/me/mrCookieSlime/Slimefun/api/Slimefun.java
src/me/mrCookieSlime/Slimefun/listeners/BackpackListener.java
src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java

Implemented async fetch for PlayerProfile
PlayerProfile.get(OfflinePlayer, Consumer<PlayerProfile>) - this has been implemented in SlimefunGuide (was lazy though so just changed openMainMenu to take a PlayerProfile and make a openMainMenuAsync). Also added a LockedCategory to accept PlayerProfile so there doesn't need to be extra hashtable lookups. Finally, implemented this into backpacks and moved some dupe code.
Also added opening messages, reason being if it will take 20+ seconds then the player will think nothing is happening and probably just spam or complain or whatever.
Timeout when player has a large profile file, no GH issue was made.

Implement PlayerProfile async fetch

---

src/me/mrCookieSlime/Slimefun/api/BlockStorage.java

A slight change to BlockStorage#refreshCache caused a block config to be loaded every time, even if it was present in the cache. This has a pretty major effect on performance. The fix is straightforward, but I'll admit I haven't tested it at all.

Fix major BlockStorage performance regression

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java

- Allow reactors to take in fuel from access port
- Allow reactors to take in fuel in bulk (similar to how it takes in coolant)
Push fuel into the reactor while decrementing fuel amount in the access port instead of just decrementing fuel amount in the access port.
Fixes #1207

Allow reactors to take in fuel from access port

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/AutoDisenchanter.java

The repair cost was applied from the item to the book.
The item repair cost is now 0 and the book has the item's repair cost. This fixes #1217 
Resolves #1217

Bring across repair cost in the disenchanter

---

src/main/java/me/mrCookieSlime/Slimefun/ancient_altar/AncientAltarListener.java

- Allow players to use the ancient altar if they have unlocked it instead of the opposite.
- Prevent ancient altar from crafting items that are not unlocked yet.
- Change the check to check if player has not unlocked. Just a minor logic change.
- Check if player already unlocked the items before crafting them using the ancient altar.
Fixes #1232

Fixed ancient alter logic

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ReactorAccessPort.java

Changed method of accessing reactor from access port. The change is made to stop inventory.no-access message when opening access port due to canOpen(Block, Player) returning false.
Added a button to access the reactor from within the access port instead of automatically opening the reactor when it is not empty.
None

Changed method of accessing reactor from access port

---

src/main/java/me/mrCookieSlime/Slimefun/GPS/GPSNetwork.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/gps/GPSTransmitter.java
src/main/java/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

1. Currently, we save the transmitter's signal strength instead of the actual Y coordinate which leads to this: https://imgur.com/hjNUxja
2. Transmitters with incorrect Y coordinate stay in memory _(in `transmitters` list)_ even after breaking until restart.
1. Transmitters now show proper Y locations.
2. Transmitters disappear from the network after breaking.
3. Replaced `double` complexity calculations with `int`s since we don't need them.

Transmitters

---

src/main/java/me/mrCookieSlime/Slimefun/Events/AutoDisenchantEvent.java
src/main/java/me/mrCookieSlime/Slimefun/Events/DisenchanterEvent.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/AutoDisenchanter.java

This is a new custom async event, which is very necessary for servers using McMMO and Slimefun. If you use McMMO, you can add +5 value of Efficiency enchant to axes/pickaxes/spades. If you put it in an item frame, and break it in the way like the enchanted item can fall into a hopper, then with a cargo it goes into the disenchanter and finally you can duplicate infinite amount of enchants.
- Added DisenchanterEvent, which is a cancellable event. With this, a new feature could be made, with you can configure whether an item could or couldn't be disenchanted.
- Added a check in AutoDisenchanter, so if the event was cancelled then the function returns.

AutoDisenchantEvent

---

src/main/java/me/mrCookieSlime/Slimefun/api/PlayerProfile.java

The command /sf stats showed only the lowest or highest slimefun title, this pull request fixes that so the full range of titles is available.
Fixed the getTitle method in PlayerProfile.
- [ x] I have fully tested the proposed changes and promise that they will not break everything into chaos.

Fixed the getTitle method.

---

src/main/java/me/mrCookieSlime/Slimefun/SlimefunPlugin.java

Fixes the researching not being enabled by default during the first load due to missing config files in the plugin's folder.
Changed loading order to register the researches first and then get the "enable-researching" setting.
Should prevent issues like #1261.

Changed loading order

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/AutomatedPanningMachine.java

Iron Nuggets and Soul Sand drops can be obtained from the Automated Panning Machine, but this is absent from the guide. This is just a small addition to show them in the recipes.
* Placed Sifted Ore before Clay, as it has a higher drop chance
* Added Gravel → Iron Nugget
* Added Soul Sand recipes (Quartz, Gold Nugget, Nether Wart, Blaze Powder, Glowstone Dust, Ghast Tear)
None

Updated recipes for Automated Panning Machine

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java

Fixes this by not adding a null item to the recipes anymore. Not sure if there was any ACTUAL use from this but from testing there aren't any issues.
Simply removed adding `null` to `recipes`.
Fixes #1272 & #1273

Fixes #1272 & #1273

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java

Fixes this by not adding a null item to the recipes anymore. Not sure if there was any ACTUAL use from this but from testing there aren't any issues.
removed if (list.size() % 2 != 0) list.add(null);
#1276

actually fixes it now

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/geo/GEOMiner.java

fixes the dupe actually now by removing 
if (displayRecipes.size() % 2 != 0) displayRecipes.add(null);
removed
if (displayRecipes.size() % 2 != 0) displayRecipes.add(null);
discord issue reported

fixes dupe with geominer

---

src/main/java/me/mrCookieSlime/Slimefun/Events/AndroidMineEvent.java
src/main/java/me/mrCookieSlime/Slimefun/androids/ProgrammableAndroid.java

Added AndroidMineEvent so in a thirdy party plugin we can cancel the mining if it's e.g. a creative placed block.
- Added AndroidMineEvent
- Added calling the event inside ProgrammableAndroid#mine()
NA

AndroidMineEvent

---

src/main/java/me/mrCookieSlime/Slimefun/GPS/Elevator.java
src/main/java/me/mrCookieSlime/Slimefun/GPS/TeleportationSequence.java

Changed the final teleportation sound to the beacon activate sound and changed the ambient teleportation sound the the beacon ambient sound
Added the end bracket to the “color codes are supported” thing for elevators (could not find the file that Holograms use)
As described above 
Couldn't find any
I can’t seem to check the boxes, but yes I did both.

Updated Teleport Sounds and Fixed The “color codes are supported text” for elevators 

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/Crucible.java

General issue: my players decided to use the Crucible under the water which leads to lava being converted to the obsidian immediately. Slimefun tries to set the block's data which throws the following warning quite a lot: https://pastebin.com/KnzAzEMH
It also allows getting multiple obsidians if you've got a good enough pickaxe.
*(same while converting leaves to water, but no one would actually use that)*
And so I ended up tweaking Crucible's mechanics.
- Crucible will stop its post job if the condition is met *(fluid was gone after setting block's type)*.
- The warning won't be thrown again.
- No more double *(or even more)* obsidian/stone *dupe*.
- Some extra checks.
- Set block to obsidian/stone *(depends on fluid's level)* when setting water upon lava and vice versa.
- Just refill …

Updated Crucible's mechanics

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/GrindStone.java

Removed two recipes for Grind Stone as we already add them while initializing corresponding items in SlimefunSetup.
Resolves #1289.

Fixed duplicate Grind Stone recipes

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/Research.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/KnowledgeTome.java

Knowledge Tome is broken :P
But now it shouldn't be!
- Reworked Knowledge Tome.
- Updated to work with the new item system.
- You can't consume the book if it's your Tome anymore.
- Changed unlocking method, you'll be able to see the researches and fireworks upon unlocking.
- Tweaked instant researching.
- You won't see the first researching step, just the message about unlocking and the fireworks.
N/A

Reworked & Fixed Knowledge Tome and a minor researching tweak

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/ExplosivePickaxe.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/ExplosiveShovel.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/HerculesPickaxe.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/LumberAxe.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/PickaxeOfVeinMining.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/SmeltersPickaxe.java
src/main/java/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
src/main/java/me/mrCookieSlime/Slimefun/androids/ProgrammableAndroid.java

Fix drops in 1.15
Replace calls to `block.getDrops()` with calls specifying the correct tool ItemStack
#1306 #1304 #1303
Some of these issues describe multiple problems with 1.15, not just this one
I only did basic testing, but it seems to have fixed the issue. I don't think it'll break any addons, but some of them will probably need the same fix applied

Fix drops in 1.15

---

src/main/java/me/mrCookieSlime/Slimefun/listeners/DamageListener.java

Allow basic circuit boards to drop when drop-from-golems is true.
Change the check to allow basic circuit boards to drop when drop-from-golems is true instead of the opposite. Minor logic change.
None

Fix Basic Circuit Board not dropping

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/AutomatedCraftingChamber.java

The changes below enable players to craft the last remaining shaped recipe in an Automated Crafting Chamber instead of having to pull out items, find an Enhanced Crafting Table, put the items back in the same order and craft them then pull the resulting output out. With the help of a single button press, these 5 steps are just two. Press the button, and take the output!
- A new method, tickOnce() that does the same work of tick(), except that it doesn't return at ItemStack amount of 1, actually it especially targets amounts of 1.
- Refactored the common code between the two methods tick() and tickOnce() into
- getSerializedInput(BlockMenu, boolean) and
- testInputAgainstRecipes(Block, String);
New Addition.
- [ X ] I have fully tested the proposed changes and promise that they will not …

Enable Automated Crafting Chamber To Craft Last Shaped Recipe

---

src/main/java/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

Normalizes the formatting of the item creation.
Turned some repeated spaces hiding as tabs into actual tabs.
new ItemStack [] -> new ItemStack[]
new ItemStack[]{. . .} -> new ItemStack[] {. . .}
If the item's recipe produces more than 1 item, 
it now follows the format: `recipe, \n\t\tnew CustomItem(. . .)`

Normalize formatting of SlimefunSetup.java

---

pom.xml

Prevent build error due to unrecognized artifact `maven-source-plugin` in pom.xml & for proper maven configuration's sake
- Add latest version property to maven-source-plugin

Add latest version property to maven-source-plugin

---

src/main/java/me/mrCookieSlime/Slimefun/SlimefunGuide.java

Fixed can't use back button in setting opened by command
Changed openGuide method.

Fixed can't back in setting opened by command

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java

Fixed magician talisman can't give book extra enchantment
When you try to enchant a book with magician talisman, It will throw java.lang.IllegalArgumentException because book is marked as unenchantable item, made enchantments list size become 0.

Fixed magician talisman can't give book extra enchantment

---

src/main/java/me/mrCookieSlime/Slimefun/Setup/SlimefunManager.java

I fixed Soulbound Runes by correcting a mistake in SlimefunManager.
Before: `item.getItemMeta().getLore().equals(ChatColor.GRAY + "Soulbound")`
After: `item.getItemMeta().getLore().contains(ChatColor.GRAY + "Soulbound")`
Because `getLore()` returns a list and not a string, `getLore()` and `ChatColor.GRAY + "Soulbound"` would never have been equal. This prevented soulbound runes from functioning. This change fixes them.
Fixed Soulbound Runes
Resolves #1553

Fixed Soulbound Runes

---

src/main/java/me/mrCookieSlime/Slimefun/api/SlimefunItemStack.java

Add getItem() to SlimefunItemStack
Added a nullable getItem() to SlimefunItemStack
N/A

Add getItem() to SlimefunItemStack

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AncientAltarCraftEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AncientAltarOutputEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/AncientAltarTask.java

Added:
AncientAltarOutputEvent: This event will trigger before the ancient altar gives you an item. This will allow you to modify which item you want it to drop, get the location of the ancient altar block or even cancel it, so that the item isn't dropped and the drop animation for the item is cancelled.
Also, documented it, in case someone wanted to yell at me because of that.

AncientAltarOutputEvent added

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemListener.java

The Block Inventory now only opens when not sneaking or when holding air in the hand
This brings the behavior in line with vanilla containers like chests
Additionally to the changes mentioned in the description, the event is now no longer cancelled when when the check fails, to enable actions like placing a block against a Slimefun Inventory Block which previously always failed even when sneaking
I removed the check if the ItemStack of `event.getItem()` is null, as with the current implentation of `PlayerRightClickEvent` this is not possible. Nevertheless i would like to see a guarantee for this circumstance added in the documentation of `PlayerRightClickEvent`
The check for placing cargo nodes has also been removed, as it is now possible to place them against the block while sneaking …

Changed Inventory opening behaviour

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java

Changed the automated ignition chambers recipe because people didnt use it because its not that usefull vs a observer + dispenser
changed the recipe also formated it a little
N/A

Change Automated ignition chambers recipe

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/Research.java

Instead of having to do registerResearch(Research, ItemStack...) you can just do new Research(..., items).register()
Makes this more consistent with the other registering too.
Varargs in constructor calling addItems
N/A

Easier to register items

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java

The issue come from calling the "equals" method on item slots for the armor. those return null when no armor is present, raising an exception.
Calling the method equals on the broken item to compare to the armor slot
Resolves #1843
- [x ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ x] I followed the existing code standards and didn't mess up the formatting.

Resolves #1843

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java

Duplication works because
1 prismarine brick = 4 prismarine,
1 prismarine = 4 prismarine shards
Therefore, 1 prismarine brick could have 32 shards, which can craft 2 prismarine brick and have some remaining left.
Changed that 1 prismarine brick will give 2 prismarine instead of 4
Resolves #1851 
- [✓] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [✓] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [✓] I followed the existing code standards and didn't mess up the formatting.
- [✓] I did my best to add documentation to any public classes or methods I added.

Fixes Prismarine Brick duplication with Grind Stone #1851

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/Talisman.java

Root cause: Removes wrong item from enderchest
Fixed the correct item should be remove from enderchest
Resolves #1893 
- [✓] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [✓] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [✓] I followed the existing code standards and didn't mess up the formatting.
- [✓] I did my best to add documentation to any public classes or methods I added.

Fixed Consumable Ender Infused Talismans don't get consumed #1893

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/BackpackCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java

Small change in BackpackListener, small fix in BackpackCommand
Made BackpackListener#setBackpackId accept OfflinePlayer instead of Player;
BackpackCommand had the wrong player passed to it too making the Backpack the sender's, fixed that.
None on GitHub, reported in #questions: https://discordapp.com/channels/565557184348422174/565569972697301020/710745009992892446

setBackpackId param type change, fix in bp command

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNet.java

Couldn't repro this issue and changing frequency in file causes it to fail on load rather than tick so... yeah. I assume this works as intended.
(Also, yes, done on laptop this time not browser so Sonar wont bitch)
Added world and x,y,z to the error so that someone can fix it more easily.
Not sure if a String#format would be better here (Or better yet, taking one of my utils and using that for formatting instead).
N/A

Add location data to caro frequency error message

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosivePickaxe.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveShovel.java

Fix compatibility with other plugins firing bukkit explosion event to do not drop near blocks on pickaxe area if the block was removed from explosion event.
Instead to check only for block break, fire explosion event using the blocks from explosive pickaxe area.
Not open already, as i am a developer of the plugin usim together SlimeFun and done fixing before open an issue.

Fix compatibility with other plugins / Explosive Pickaxe

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/UpdaterService.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java
src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java
src/test/java/io/github/thebusybiscuit/slimefun4/tests/services/TestUpdaterService.java

Adds the ability to reload a BlockMenu and adds the ability to retieve the build number of SF.
BlockStorage now has a `reloadInventory(Location)`, BlockMenu has `reload()`. Also, CargoUtils has a way to get the blacklist/whitelist slots for addon use.
UpdaterService now has a #getBuildNum which allows addon devs to do things like `if (stable && buildNum >= 11) // add item`. They should of course also tell the server owner to update SF but it allows the addon to still function without being completely disabled.
N/A

Add a way to reload BlockMenu

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java

Butcher Android deals wrong amount of damage.
Tier1/2 deals 20dmg, and Tier3 deals 12dmg.
It is different from Android item lore.
Just change Inequality sign.
None.

Fixed android ATTACK part deals wrong damage

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricIngotPulverizer.java

Adding a recipe to Electric Ingot Pulverizer for converting vanilla Gold Ingot to Gold Dust.
Added `registerDefaultRecipes()` - most of the recipe addition for Smeltery & Pulverizer are handled in `PostSetup.loadSmelteryRecipes()` - so it made sense to create this method here as a "special case".
No issues created for this - there was a separate conversation with TheBusyBiscuit in Slimefun-Wiki and I think this is a good addition to the Pulverizer anyway.

Adding recipe for vanilla Gold Ingot -> Gold Dust conversion

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/ErrorReport.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/BackupService.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/PerWorldSettingsService.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubConnector.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/ChestSlimefunGuide.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Script.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/MagicianTalisman.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/ActiveMiner.java
src/main/java/me/mrCookieSlime/Slimefun/SlimefunPlugin.java
src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset.java

1. Some plugins may create fake worlds. For example, AWE can do that after the first usage of `//regen`. Those ghost worlds aren't handled by Slimefun (they do not exist during startup and world load event is not fired for them too), so there was an error when the plugin was trying to save them.
2. There's a minor chance for NPE when saving block data. See related issues.
3. Fixed a tiny typo that was annoying me.
1. Slimefun now tries to save data only for registered worlds.
2. Slimefun now handles possible NPEs. There will be a warning instead.
3. `occured` -> `occurred`.
See https://github.com/TheBusyBiscuit/ExoticGarden/issues/123 as an example of point 2 above.
*Wow, there are more checkboxes now! I wasn't contributing to Slimefun code-wise for quite a while :o*

 Improve the handling of non-registered worlds

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/api/network/Network.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/TimingsCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/package-info.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNet.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ChestTerminalNetwork.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubTask.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/plugins/PlaceholderAPIHook.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/PerformanceRating.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/PerformanceSummary.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/ProfiledBlock.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/package-info.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/EnhancedFurnace.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/CargoManager.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/DebugFishListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/ChestMenuUtils.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java
src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
src/main/java/me/mrCookieSlime/Slimefun/api/EmptyBlockData.java
src/main/java/me/mrCookieSlime/Slimefun/api/energy/ChargableBlock.java

This Pull Request adds a proper Lag Profiler to Slimefun.
The previous implementation was very clumpy and done on top of an even older system.
It featured quite a few concurrency issues, reported inaccurate timings, missed out on cargo networks and other stuff but most importantly... due to the maintenance of so many ConcurrentHashMaps with many operations per block... it added quite an overhead to the system.
This PR adresses this issue and adds a proper thread-safe profiler.
The profiler uses a Threadpool ExecutorService to distribute its load and calculations, it can even pick up sync AND async tickers and is overall much more accurate and maintainable.
*Oh, and since this commit was in my back log and I forgot it was there... Gilded Blackstone was added to the Ore Crusher :o*

Changes to performance, added a proper Lag Profiler

---

CHANGELOG.md
pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/TeleportationManager.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ChestTerminalNetwork.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Composter.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/gps/ElevatorPlate.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AbstractSmeltery.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AutomatedPanningMachine.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Juicer.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreWasher.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/PressureChamber.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Smeltery.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/ActiveMiner.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PickaxeOfContainment.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/DispenserListener.java

This Pull Request introduces a bunch of optimizations for Servers using [Paper](https://github.com/PaperMC/Paper).
Paper uses Asynchronous Chunk Generation/Loading which can improve performance for long-distance teleports.
Normally, Spigot creates a new BlockState instance as a hard copy, for InventoryHolders the Inventory is only copied softly, as a reference. Since Inventories are already Thread-safe and only the reference is passed, cargo networks have no reason to create a BlockState snapshot. 
This behaviour cannot be avoided when using Spigot, with Paper it can.
So this will improve performance drastically (Sometimes up to 6 times smoother from what i tested) and optimize Cargo networks to work best when using Paper.
* Added [PaperLib](https://github.com/PaperMC/PaperLib) as a …

Optimizations for Paper (cargo network optimizations)

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java

Currently Ancient Debris is not able to be mined by Industrial Miners. This PR allows for that.
- Ancient Debris can now be mined by Industrial Miners.

Allow Ancient Debris to be mined by Industrial Miners

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java
src/main/resources/languages/messages_en.yml

As I promised, here's my fix for #2122. My previous fix was a bit unclear on user-side, so I went back to InventoryClickEvent.
This prevents Slimefun items from being added to a Brewing Stand as an ingredient.
- Added a more detailed check to the onPreBew() handler
- Added a deny message when a player is about to use Slimefun items as an ingredient
Fixes #2122

Fixed prevent Slimefun items from being added to a Brewing Stand

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java

Changed the canMine() method to check the name of the material. I think this is cleaner than using MinecraftVersion.isAtLeast() here. I also think that this change is enough, the upper getOutcome() method should be fine.
- Changed canMine() in the class IndustrialMiner
Fixes #2203

Fixed Industrial Miner debris issue

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java

This will prevent putting items into the android script editor GUI by using hotkeys.
- Set empty slots not clickable in the script editor ChestMenu of the programmable android
Fixes #2243

Fixed android script editor menu hotkey glitch

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java

There's a very old infinite lava duping bug made by fluid pump, dispenser and a timer. This fixes it by only checking for source blocks.
Made fluid pump consume only source blocks.
N/A on Github.
Note: I didn't test these changes and made them from my mobile phone, so yeah.

Fixed Fluid Pump dupe.

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/WindStaff.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/CoolerListener.java
src/main/resources/languages/messages_en.yml

Made coolers also saturate the player when they get hunger damage.
Made it so when a player gets hunger damage they use their cooler.
Fixes #2263 
Note: I did these changes ftom mobile. So yeah... it needs testing and I can't do that.

Fixes #2263

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/ChargeCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/SlimefunSubCommands.java
src/main/resources/languages/messages_en.yml
src/main/resources/plugin.yml

This command charges the item that the sender is holding to max. It is intended to be used for admins on servers or testing items.
Added ChargeCommand subcommand class, added command description, a success message, and a fail message to messages_en.yml, and added command to plugin.yml.
N/A
*This PR only adds a small change, so the entire thing is essentially a Unit Test.

Added /sf charge

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/geo/ResourceManager.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuideLayout.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/GuideLayoutOption.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SupportedLanguage.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/PerformanceRating.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Instruction.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/HeadTexture.java
src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/utils/TestHeadTextures.java

Done some good old micro-optimisations for build #666, pls no [CI Skip]. I ask for so little.
* For Enums I have added a global variable to avoid the value array being copied every time `values()` is called.  
Bytecode showing the array is cloned:
```
public static io.github.thebusybiscuit.slimefun4.implementation.items.androids.Instruction[] values();
Code:
0: getstatic     #1                  // Field $VALUES:[Lio/github/thebusybiscuit/slimefun4/implementation/items/androids/Instruction;
3: invokevirtual #2                  // Method "[Lio/github/thebusybiscuit/slimefun4/implementation/items/androids/Instruction;".clone:()Ljava/lang/Object;
6: checkcast     #3                  // class "[Lio/github/thebusybiscuit/slimefun4/implementation/items/androids/Instruction;"
9: areturn
```
* …

Micro-optimisations for #666

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/GEOResourceGenerationEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/MachineProcessCompleteEvent.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java

Added MachineProcessCompleteEvent, which fires whenever an AContainer has completed its process. This was the best name I could came up with. If you have a better idea, then tell me.
I can add a Unit Test, if needed.
- Added MachineProcessCompleteEvent.class
- Fixed a small typo in GEOResourceGenerationEvent.class
- Added the #callEvent() method to AContainer.class
- Finally a minor impovement in AContainer.class
N/A

MachineProcessCompleteEvent

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncMachineProcessCompleteEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/MachineProcessCompleteEvent.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java

Made the event async, because it is called asynchronously. I didn't notice this tbh, but here I am with the fix.
- Made MachineProcessCompleteEvent async
- Renamed to AsyncMachineProcessCompleteEvent
Fixed that this sync event was called asynchronously, so I made it async.

Made MachineProcessCompleteEvent async

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunGuideListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/itemstack/SlimefunGuideItem.java

Fixed non-colored string in Cheat Sheet lore
Fixed Shift + Right Click on Cheat Sheet not opening Settings Menu instead 
Added missing coloring to lore in SimefunGuideItem
Added check in SlimefunGuideListener for sneaking in order to open Settings Menu
N/A

Fixed colors & functionality of cheat sheet

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncGeneratorProcessCompleteEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncMachineProcessCompleteEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncReactorProcessCompleteEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java

Added AsyncGeneratorProcessCompleteEvent which fires whenever an AGenerator has completed its process.
Added AsyncReactorProcessCompleteEvent which fires whenever a Reactor has completed its process.
Also, I changed AsyncMachineProcessCompleteEvent a little bit to be more cleaner.
This time I tested every change carefully.
- Added AsyncGeneratorProcessCompleteEvent
- Added AsyncReactorProcessCompleteEvent
- Minor improvement in AsyncMachineProcessCompleteEvent
N/A

Added AsyncReactorProcessCompleteEvent and AsyncGeneratorProcessCompleteEvent

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/BackpackCommand.java

All other commands have a separate message for player-only and no-permission messages, while backpackcommand instead just sent a no-permission message for both cases. I have split it so it sends the appropriate message for the appropriate case.
Split checks in BackpackCommand.java for `no-permission` and `player-only` messages
N/A

Separate player-only and no-permission messages

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GrapplingHook.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GrapplingHookEntity.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GrapplingHookListener.java

[+] Added a setting to allow the grappling hook to stay in inventory instead of being dropped on the floor on use
I added an item setting to allow players to set if they want the grappling hook to drop on the floor on use or just stay in the inventory. I did this because I use slimefun on a small server with friends and they complained about the grappling hooks dropping on the floor as annoying
[+] Item Setting named "stay-in-inv-on-use"
None

Pull request for an additional customizable option in grappling hooks

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java

Added a cancelled ItemUseHandler to prevent placing Magical Zombie Pills.
Added a cancelled ItemUseHandler.
Fixes #2359

Magical Zombie Pills place fix

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GoldPan.java

Added a cancelled EntityInteractHandler to prevent interacting GoldPans with entities.
- Added a cancelled EntityInteractHandler
Fixes #2356

Fixed GoldPan entity interaction

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java

Attempt to fix a bug where refineries can be used as pistons
Checks if the following condition has been met (Check if the event fired on a piston that has Slimefun block data)
```java
BlockStorage.check(e.getBlock()) != null
```
Resolves #2360

Attempt to fix bug #2360

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/ChestSlimefunGuide.java

Added a check to ChestSlimefunGuide#getVisibleCategories that adds SeasonalCategories to Cheat Sheets. I think this is logically fine, but if it could be simplified then tell me.
<details><summary><b>Some screenshots (Click me!)</b></summary>
</img>
Haha, in less than a month:
TheBusySanta:
</details>
- Added seasonal categories to the Cheat Sheet
Resolves #2316

Added seasonal categories to the Cheat Sheet

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java
src/main/resources/languages/messages_en.yml
src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestVanillaMachinesListener.java

Added an EventHandler to `VanillaMachinesListener` class to prevent Slimefun items from being used in Cartography Tables.
- Added `onCartographyTable()` EventHandler to `VanillaMachinesListener` class
- Added Unit Tests
- Added `cartography_table.not-working` message to `messages_en.yml`
Fixes #2357

Cartography Table fix

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java

Add all Carat Gold types to the Ore Crusher. As suggested (and approved) on the Discord.
Added following recipes in the file `OreCrusher.java`, in the method `registerDefaultRecipes(List<ItemStack> recipes)`:
- 6 - 8 carat gold now yields 1 gold dust
- 10 - 16 carat gold now yields 2 gold dust
- 18 - 24 carat gold now yields 3 gold dust
<br>
These are not really viable in my situation:

Add remaining carat golds to ore crusher

---

pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoDisenchanter.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoEnchanter.java

The auto enchanter and disenchanter times can be affected by speed, so if more tiers were to be created in an addon, you could @override the speed to actually make it faster. I also fixed a pom typo.
in pom, pakages -> packages
in enchanter /disenchanter, the old time is now divided by the speed, which doesn't affect the current ones.

Speed can affect enchanter/disenchanter times, fixed pom typo

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerBackpack.java

I found this small problem in https://sonarcloud.io/project/issues?id=Slimefun_Slimefun4&open=AXTBL6kaIVI46B1gLWcP&resolved=false
I defined a new private variable for it. I am not sure about the name and also i believe that this could also be defined as static in the class.
- define private variable `backpacks`
- replace hardcoded string with the new variable
NA

Define a constant instead of duplicating "backpacks."

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/TableSaw.java

Add planks -> sticks with double yield ratio to Table Saw (as suggested and approved on the Discord)
- Add 1 plank -> 4 sticks recipes for all plank types in table saw
- Add displayrecipes for table saw
Right now I loop through all the planks to check if the held item is a plank or not, is there a better way to do this?
<br>
N/A

Add sticks recipe to table saw

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectrifiedCrucible.java

Added Blackstone and Basalt -> Lava Bucket to crucibles. Duplicate of #2398 I had closed as others had claimed the issue; as discussed in Slimefun's Discord a few days ago, due to inactivity I updated my fork and PR'ed once again.
Added Blackstone -> Lava and Basalt -> Lava to Crucible and Electrified Crucible. Following @LinoxGH's suggestion in #2398 I made the recipe cost half as many blocks per Lava Bucket due to materials being Nether related.
Resolves #2369 
Not applicable:

Added Basalt + Blackstone to Crucible

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java

Nether Goo now changes an ordinary sheep to **Tainted Sheep**.
- When applied to a Sheep without a CustomName, it renames that Sheep to **Tainted Sheep**.
- Changes wool color to **PURPLE**.
- Gets poisoned for 3 seconds with _Poison PotionEffect II_.
Added `addItemHandler(onRightClickEntity())`
Resolves #2414

Nether Goo "Tainted Sheep"

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Instruction.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java

I changed the access modifiers in `ProgrammableAndroid.getScript()` and `ProgrammableAndroid.setScript()` from protected to public so external addons can change android scrips (I need it for precisely that reason). I also changed `Instruction` enum to public
`ProgrammableAndroid.getScript()` and `ProgrammableAndroid.setScript()` are now public
`Instruction` is now public
None

Changed some things to public (from protected)

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java

AContainers will now check and take charge when they are outputting, not just when progressing.
Added a method to check and take the charge ,called it before outputting
Resolves #2509

Fixes #2509

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/AnvilListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/BrewingStandListener.java

Anvil Listener had doc comment copied from Brewing Stand.
Changed one link
N/A
N/A:

Smallest documentation fix ever

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/PlayerPreResearchEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/PreCanUnlockResearchEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/researching/Research.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/BookSlimefunGuide.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/ChestSlimefunGuide.java
src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/researches/TestResearches.java

This event is called when a player click to unlock a research
This is called called before Research#canUnlock(Player)
The event is not called for the cheat sheet
This even can be very useful, with it, devs can deactivate the default research system and if they want, add their own system. 
- Created the Event
- Add the callEvent before canUnlock in ChestSlimefunGuide and BookSlimefunGuide
- Changed the order of canUnlock and hasUnlocked (hasUnlocked now before). After some tests, this doesn't cause any problem, and now, if a player open a guide, receive a research by an admin, and then click on the item to receive the research, there won't be a red message with not enough xp send to the player

Added PlayerPreResearchEvent

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/BlockPlacer.java

Fixed a bug of Duplicate items with BlockPlacer's delay
on BlockPlacer place an item, just take out the item when it place,then one in hand and 
another is placed.
when BlockPlacer place,there shouldn't be someone viewing it.
I have no better way to fix it.
With BlockPlacer's Place delay,it can Duplicate almost any block,just take out the item in BlockPlacer on BlockPlacer place.

Fixed a bug of Duplicate items with BlockPlacer

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

Fixes instances of ghost blocks (places where you can't place blocks, because for SF it exist and for server not).
As for now I did quick test of it and it looks like everything worked. I also plan to test in on working server soon.
Added some logic to BlockListener.onBlockPlaceExisting for checking if targeted block is air (and if it is, removing it and dropping item).
https://github.com/Slimefun/Slimefun4/wiki/Common-Issues#unplaceable-blocks
https://youtu.be/HYlNRKud5kI
^ Leaving this empty, as I prefer someone else to rate it (1st and 2nd one I will check after tests).

Fix ghost blocks

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/TimingsCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/PerformanceInspector.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/PerformanceSummary.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/inspectors/ConsolePerformanceInspector.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/inspectors/PlayerPerformanceInspector.java
src/main/resources/languages/messages_en.yml

@WalshyDev wanted this.
Also finally added locale to the /sf timings command. Added an abstract framework to allow for future flags too.

Added verbose flag to /sf timings

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/SlimefunCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/InfusedHopper.java

The Infused Hopper would think that an item with pickup delay of 32,767 is valid. Items with a delay of 32,767 are marked as non-pickupable by the MC client and server. We should treat them the same, there are many plugins which use this in order to say their items shouldn't be picked up.
MC Wiki Ref: https://minecraft.gamepedia.com/Item_(entity)#Entity_data
* Added a pickup delay check to InfusedHopper#isValidItem
* Fixed a typo in the class Javadoc
Skizzles on Discord: https://discord.com/channels/565557184348422174/565569196218384385/799931483635580959

Fix the infused hopper picking up items with pickup delay Short.MAX_VALUE

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
src/main/resources/languages/messages_en.yml

I added a script length check right before opening the edit script page. The reason for this is that in an addon I'm making, I can set much longer scripts than 54 instructions.
Added a script length check
N/A

Added script length checking

---

pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/api/ErrorReport.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/SlimefunGuideSettings.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/Configuration/Config.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ClickAction.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/Item/CustomItemSerializer.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/Item/ItemFlagComparator.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/MenuListener.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/package-info.java
src/main/java/me/mrCookieSlime/Slimefun/api/BlockInfoConfig.java
src/main/java/me/mrCookieSlime/Slimefun/api/EmptyBlockData.java
src/main/java/me/mrCookieSlime/Slimefun/package-info.java
src/main/java/me/mrCookieSlime/package-info.java
src/main/resources/plugin.yml
src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestItemPickupListener.java

For ~3 years we have been slowly but surely getting rid of the old CS-CoreLib code (CSCL 1 that is).
Sure, a lot of addons may still use methods from CSCL 1 but I made sure to transfer the three main classes that are still in use.
Note here that CSCL 1 has basically remained untouched since 2018 and bStats shows that literally **noone** is running any outdated versions. So the classes should all match, in case someone still uses CSCL1 (though, our classes should take priority when loaded...), the class signatures should still be compatible.
This may need much more testing though before this is ready to be merged.
We may announce this as a public beta.
* Removed CS-CoreLib dependency from the `pom.xml`
* Removed CS-CoreLib as a `softDepend` from the `plugin.yml`
* Removed check for …

Experimental: Slimefun but without CS-CoreLib

---

src/main/java/me/mrCookieSlime/Slimefun/api/inventory/DirtyChestMenu.java

As mentioned in CS-CoreLib2's numbers 141 and 142 PR's, previous iterations of Slimefun AContainers would not consider the underlying Inventory's max stack size when determining sizing or pushing items. This commit changes DirtyChestMenus to act similarly by storing a variable defined as the lower of the Inventory's max stack size and the ItemStack's max stack size in a slot.
* Changed `else if` statement in line 108 to an `else`
* Defined variable `maxStackSize`
* Resumed original conditional statement
* Changed all references of `stack.getMaxStackSize()` to `maxStackSize`
N/A

Check inv maxStackSize

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricSmeltery.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/HeatedPressureChamber.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java

Register machine's recipes when #register() called instead when initializing.
In newer version of Slimefun, set machine's speed need call #setProcessingSpeed().
But the progress of configuring speed is in register items, which caused the speed is
-1 when register recipes.
Register machine's recipes when #register() called instead when initializing
Removed init register recipes call in Electric Smeltery and Heated Pressure Chamber
Use comparator in Electric Smeltery and Heated Pressure Chamber
Resolves #2761

Fix #2761 probably

---

.github/workflows/pr-labels.yml
CHANGELOG.md
pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
src/main/resources/languages/researches_ja.yml

Provide a way to access BlockStorage's `storage`. This adds a way to access all the blocks loaded in the server. It may be worth making this return an immutable map so that people don't modify this. Let me know your opinion.
This is currently untested (though if it compiles, can't see why it wouldn't work) and I made this on my phone sooo compilation may fail. Not added tests or docs either due to phone (also this class really needs to be redone anyway)
* Added BlockStorage#getStorage
* Added BlockStorage.getStorage(World)
N/A

Add a way to retrieve the raw storage

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/Talisman.java
src/main/resources/config.yml

Long-requested feature; Talismans can now send their messages using the actionbar.
This is configurable but reduces spam :)

Allow Talismans to use the Actionbar

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java

Add the Java version to `/sf versions` and add some hover text to it if using a version lower than 11. I also added hover text to disabled plugins.
Image of full versions:
Image of Java hover text (Need suggestions on the text):
Image of disabled plugin hover text:
* Added "Java" to `/sf versions`
* Redone the `/sf versions` message to be a TextComponent
* Added hover text for the Java field
* Added hover text for any disabled plugins
N/A

Add java ver and hover to versions subcommand

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java

Fixed wood cutter is able to duplicate wood when unable to replant.

Fix duplicating woods when unable to replant

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlocksEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java

Added ExplosiveToolBreakBlockEvent triggered by an explosive tool breaking a block.
I need it for my addon, as it can currently break blocks without me having any event to catch.
Added ExplosiveToolBreakBlockEvent, made it Cancellable and edited ExplosiveTool to reflect that
null

Added ExplosiveToolBreakBlockEvent 

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java

Switch the two last items in the Magical Category around so that all the runes appear next to each other.
Example of how it looks now (before the last two items were switched):

Switch the last two items in Magical Items

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/SlimefunStartupTask.java

When custom worlds were loaded before a certain addon had been loaded, the BlockMenuPresets for the stored inventories couldn't be found, so the block had no inventory. When the listener is registered after all addons load, it allows all the presets to be loaded before inventories are. The BlockStorages for the worlds are still created because Slimefun is already iterating through all of the default ones during the startup task.
Moved WorldListener creation from registerListeners to SlimefunStartupTask
Resolves #2862

Fix addon blockmenu loading with custom worlds

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

Added a check for if the BlockBreakHandler was cancelled and returned accordingly. This prevents Slimefun block data from being cleared when the BlockBreakEvent gets cancelled within the handler.
Modified BlockListener.java to return if the BlockBreakEvent is cancelled.
N/A

Allow onBlockBreak to be cancelled by BlockBreakHandler

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java

Fixed the bug in #2903 where crucibles next to each other doesnt work due to the output updating each other causing the liquid to be updated.
Made applyPhysics false when running block.setType
Fixes #2903

Fixes #2903

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncMachineProcessCompleteEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/BlockPlacer.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoDrier.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/CarbonPress.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/AnimalProduce.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/ProduceCollector.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AutoCrafterListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
src/main/resources/languages/researches_en.yml

Added the Produce Collector.
This machine can fill up buckets with milk and bowls with mushrrom stew if a nearby Cow/Mooshroom is found.
Also fixed a bug in the Auto Crafter which consumed the milk instead of leaving a bucket behind.
And allowed Block Placers to place cake (special case that I really wanted)
All of this makes for a nice completely automated cake factory.
When you eat the cake, it is immediately replenished by the Block Placer below.
* Added Produce Collector
* Fixed Auto Crafters not handling milk buckets properly
* Allowed Block Placers to place down cakes
* Fixed Multimeter not working on Auto-Crafters

The update that fixed world hunger (or how I made a cake factory)

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SoulboundListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java

I thought this was a pretty good and simple fix, I have made another method in SlimefunUtils for isSoulbound which accepts a world. If the item is a SF Item and it has been disabled in that world then soulbound returns false. The same as if it was disabled in general.
Added a unit test to cover this case as well.
* SlimefunUtils.isSoulbound(ItemStack, World)
* SlimefunUtils.isSoulbound(ItemStack) now calls isSoulbound(ItemStack, null)
Resolves #2650

Fixed 2650

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/LocalizationService.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/Language.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java

In the case of calling `Localization#getMessage(String)` there was no override in SlimefunLocalization meaning that no fallback was done.
Also fixed an issue with an invalid validation (https://github.com/Slimefun/Slimefun4/pull/2956/files#diff-b74eb692f379f300a12715d1a757f82e7aaeaa379276b8b528a5e78543a298beR155). Added some extra validates too.
* Fixes #2942 
* Fixed incorrect Validate
* Added more Validates
Resolves #2942

Fixes #2942

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/CarbonPress.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java

Compressor and Carbon Press now accept 8 coal blocks and use those to craft 9 carbon. This is useful when moving and processing large amounts of coal.
Carbon Press coal block recipe gives no processing speed or product amount advantage over using the standard coal one. (9x slower, 9 carbon).
- Added recipe to the Compressor multiblock
- Added recipe to the CarbonPress machine
none, Discord suggestion 915

Add Block of Coal -> Carbon recipe to the Carbon Press and Compressor

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java

Talisman of the anvil throws NPE if the select hand slot is empty.
Switch the order of checking for equality as the broken item is always not null.
Resolves #2987

Fixes NPE when hand is empty while talisman of the anvil triggers

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java

Auto Enchanter now considers both combinations of enchanted book and item (item in first or second slot).
The machine now tries to check if the second combination could possibly be valid instead of exiting immediately as before.
Uses `addUnsafeEnchantments` instead of `addUnsafeEnchantment` to skip the loop over map entries.
Uses `isEmpty` and `map.size()` instead of a separate amount variable.
Resolves #2977

Fixes #2977

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/GuideHistory.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java

Keeps the main menu page history saved
Added a main menu page field to GuideHistory, added getters and setters. When the guide is opened, it sets the main menu page to the page it was opened to.
Fixes #2593

Main Menu Page History Fix

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java

title
Added null checks when getting the block menu for the android block
Fixes #2937

Fix android click handler errors while moving

---

.github/ISSUE_TEMPLATE/bug-report.yml

I have no idea if you can still have the old markdown format alongside this, I would assume so. This just brings over the current structure without any real changes.
Full documentation can be found here: https://gh-community.github.io/issue-template-feedback/structured/
Changelogs are also on that same site

New form-based Issue templates

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java

This change allows lumps to be stored more easily and also helps when too many certain lumps are crafted by mistake.
4 new recipes in the GrindStone
Discord suggestion 1183

Add grinding of higher level lumps back into 4 lower level lumps

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java

Previously, a slimefun block could only be destroyed by an explosive tool's blast radius if the item had no
BlockBreakHandler. Now, it will correctly break it as long as the handler doesn't cancel the dummy event, or if there is no handler.
Moved callItemHandler out of if statement
Fixes #3036

Fixed explosive tool handling for blocks with a BlockBreakHandler

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/ExplosiveBow.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/IcyBow.java

Resolves #3060
When a player holding a shield is hit with Icy Bow, the effects still apply
Check for final damage caused and if the player hit is blocking
Resolves #3060

Fix Icy Bow ignores shields

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GoldPan.java

Resolves #3064
When a chance for any item in a `GoldPan` is set to 0, our validation allows it but validation in the `RandomizedSet` does not.
Add a simple check to `updateRandomizer()` in `GoldPan`
Another option would be to update `RandomizedSet` in cscorelib to accept/handle zero chance values.
I have also tested the case when all drops are set to zero.
This could happen in the `FishermanAndroid` in the future as it also uses the `RandomizedSet` but for now, its chances aren't configurable.
Resolves #3064

Fixed an Exception when any GoldPan drops have zero chance of dropping

---

src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java

Stored inventories were getting loaded multiple times, overwriting the previous ones each time. Universal menus and stored chunks aswell. This is intended to be a temporary fix while BlockStorage is hopefully deleted and rewritten lol.
Added 2 checks to see if chunks and UniversalBlockMenus have already been loaded, and a check for world when loading BlockMenus.
Fixes #2979

Fixed menu loading issues and probably improved BlockStorage load times

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
src/main/java/me/mrCookieSlime/Slimefun/api/inventory/DirtyChestMenu.java

Currently, players need to come up with clever ways to handle the overflow of logs from the Woodcutter Android otherwise the android will inevitably get stuck in a loop and will need to be restarted manually by adding fuel to it when it runs out.
If the android's inventory is full while in the middle of chopping a tree, the logs will 'get lost', meaning chopped successfully but not added to the android's inventory. The miner android does kind of the same thing.
Resolves #2964

Fix WoodcutterAndroid getting stuck while chopping a tree with full inventory

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientAltar.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/AncientAltarTask.java

Mass crafting rune in base Slimefun is currently very tedious. This gives the server owners the option to configure the speed themselves.
Add `IntRangeSetting` to the `AncientAltar`
Remove check for zero-tick step delay, now it is possible to craft instantly

Add a configurable step delay to the Ancient Altar

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java

This will allow slimefun items created with recipes of length less than 9 to be filled with nulls until reaching length 9 rather than being 9 nulls.
Rather than setting the recipe to a `new ItemStack[9]` when `length < 9`, set it to `Arrays.copyOf(recipe, 9)`

Easier SlimefunItem creation with small recipe

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
src/main/resources/config.yml

This PR aims to just cleanup the config a little to fix inconsistency and a case where issues can easily occur.
Slimefun is so much more optimised than it used to be. Insanely so. The 12 ticks has never made sense to me. Regardless though, this 12 tick delay has always caused issues for people due to the fact that all Slimefun lores assume this is 10 ticks. They have production * 2 in the lore.
This changed should cause no real issue due to the fact it's always been changeable anyway. No addon or core Slimefun functionality should be based on this being 12.
It has now been 2 years since this was introduced. All servers which didn't have this config option definitely do now. If we look at bStats 80% of servers have this disabled. A lot of those which have it enabled do not actually know …

Change config for consistency and improvement

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java

Added SlimefunProfiler#collectAverageTimings which will return the average ms for the given profiler. The supporting values get reset after each call.
I also fixed some validations.
This was done so that I can add this to our metrics.
* Created SlimefunProfiler#collectAverageTimings
* Have an AtomicLong and AtomicInteger which log the summed ms timings and ticks passed
* Fixed validations
N/A

Add collectAverageTimings to SlimefunProfiler

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickingBlocks.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TestTickerCollection.java

As per a discussion in the SF discord, this PR removes the use of explicit locks used in TickerTask. 
I'm not a massive fan of the implementation of `TickingBlocks` as it is right now. Currently its just been wrapped (mutex) so it isn't that much better for performance than it was before (might even be worse on that end). However, we now map the world to a long as opposed to `ChunkPosition --> Set<Location>` which means the memory footprint is considerably lower. 
- Add `TickingBlocks`, a class that serves as an accessor/wrapper for a `Map<World, Set<Long>>`. In other words, a `BlockPositionSet`. 
- Removes the public getters for the `tickingLocations`
- Swap out the `Lock` + `Map<ChunkPosition, Set<Location>>` for `TickingBlocks`
- Added relevant docs

Change the way the TickerTask tracks Blocks

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java

When the IndustrialMiner is mining in a world where the minHeight is smaller than 0, it ignores everything below 0. This is because the minWorldHeight is hardcoded.
Use `WorldUtils.getMinHeight(world)`
Discord suggestion 1405

Allow IndustrialMiner to mine when minWorldHeight is lower than 0

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java

I made this pull request because I found it logical that you should be able to grind amethyst blocks into amethyst shards, and the idea came to one of my friends while they were playing on 1.17, and they asked me to implement it in some form
I have added an Amethyst Block -> 4 Amethyst Shard recipe to the grind stone multiblock
N/A

Add Amethyst Block -> 4 Amethyst Shard recipe to grindstone

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java

Following in the footsteps of the ancient debris option, deepslate ores can now be excluded from being mined by the `IndustrialMiner`. Some people believe this will force players to go caving more instead of just ignoring the upcoming caves content.
Add a boolean ItemSetting to the IndustrialMiner
Discord suggestion 1347

Add the option to prevent IndustrialMiner from mining deepslate ores

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java

I suggested that the industrial miner should produce raw metals (iron, gold, and copper) instead of ores in 1.17, but it is not approved yet. 
Changed outcomes for industrial miner:
In 1.17, the basic industrial miner will produce raw metals (iron, gold, and copper) instead of metal ores.
In 1.17, the basic industrial miner will mine deepslate ores just like a pickaxe.
In 1.16, the basic industrial miner will produce gold nugget instead of nether gold ore.
[discord suggestion #1400](https://discord.com/channels/565557184348422174/693130800853418055/859575052173312030)

Allow the Industrial Miner to produce raw ores rather than ore blocks

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java

I suggested adding copper ore and deepslate copper ore to ore crusher in 1.17, but it is not approved yet. I also added deepslate iron and gold ores. This change allows people to crush the ores obtained with Advanced Industrial Miner.
Added following recipes to Ore Crusher (supports double-ore option):
deepslate iron ore -> iron dust
deepslate gold ore -> gold dust
deepslate copper ore -> copper dust
copper ore -> copper dust
[discord suggestion #1400](https://discord.com/channels/565557184348422174/693130800853418055/859575052173312030)

Adds deepslate iron, gold, copper ores, and copper ore to Ore Crusher

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/LimitedUseItem.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/LoreBuilder.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/PatternUtils.java

This change makes it easier for Slimefun or Slimefun addon devs to create items with a limited number of uses.
Add LimitedUseItem - base class for items with limited uses
Update StormStaff to extend LimitedUseItem
Add 'usesLeft' function to LoreBuilder
none

Add LimitedUseItem - base class for items with limited uses

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java

If you hold a shield on offhand, and a sword on mainhand.
Then when shield broken, the shield fixed by talisman anvil will replace mainhand sword.
Add validate for offhand slot
None

Fixes Talisman of anvil break main hand item in special case

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/items/ItemSpawnReason.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/PressureChamber.java

This fixes disappearing items with machines connected to almost full output chest.
These machines are: Compressor, Magic Workbench, Armor Forge, Pressure Chamber.
Added to `Compressor`, `MagicWorkbench`, `ArmorForge` and `PressureChamber` check if the items can be added to the output chest after crafting.
If items can't be added then item will be added to another output chest (if it exists). And if items can't be added to any output chests then item will be added to dispenser. And if item can't be added to dispenser then the item will drop on the ground.
Resolves #3136

Fix disappearing items with output chest by machines

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java

White items would be "similar" to renamed items used on an AncientAltar for the purposes of crafting. Further details in the Discord channel
Don't add WHITE color for no apparent reason
Resolves #3164

Fix renamed items turning into valid-ish items for crafting purposes

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/FlexCategory.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java

Currently, it is impossible to display FlexCategories in the CheatSheetSlimefunGuide.
Add checks for `isVisible()` to both the Survival and CheatSheet books in the case of a `FlexCategory`.
A better option would probably to stop using the `isHidden()` altogether and move towards `isVisible()` since `isHidden()` is used only in one place in the whole Slimefun codebase anyway but this breaking change could introduce issues for other addons.
No related issue, discussed for a bit in the programming-help channel.

FlexCategories can now be made visible in CheatSheet and Survival SlimefunGuide

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricSmeltery.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java

I am using a resource pack in my server, the background slots in some machines' gui do not act properly like those in other machines. These should use methods in `ChestMenuUtils` to let the gui with resource pack look fine to me.
Replace `GRAY_STAINED_GLASS_PANE` in chestmenu's setup with `ChestMenuUtils.getBackground()`.
Also replace input slot item with `ChestMenuUtils.getInputSlotTexture()`
and output slot item with `ChestMenuUtils.getOutputSlotTexture()`
N/A

Use chest menu preset in GUI

---

src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java

Set a pickup delay of Short.MAX_VALUE (which in the client means "never pickup"). A lot of third-party plugins (including ones like WildStacker) check for this value to know if it's a custom item or if it should be modified/stacked. Setting this prevents a lot of third-party plugins from messing with the items.
Set the pickup delay to "never pickup" in the `markAsNoPickup` method.
Resolves #3203

Fix pickup delay not being set

---

src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java

We had a `chunksLoaded` boolean, not sure why this was here but removing it did not cause any unexpected changes. This was being set to true after the first world load and then the second load, it did not load due to this.
We have a world name check so this, in theory, should not be required. If there was a reason which is still valid, we will find out soon and should do a proper fix rather than this.
I also fixed the chunk data not saving on normal shutdown
* Remove `chunksLoaded` static boolean
* Run `saveChunks` on `saveAndRemove`
Fixes #3225

Fixes #3225 and chunk data not being saved on shutdown

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java

Spigot 1.16 introduced Inventory#isEmpty. Since we support 1.14 and 1.15 we don't want to call this on those versions. This introduces a small util method and fixes a place where Inventory#isEmpty was called.
This introduces a small util method and fixes a place where Inventory#isEmpty was called.
Resolves #3206

Fixes #3206

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java

Fixed the recipe for enderlump as the guide says to use enhanced crafting table (Which is incorrect)
Previously made a PR via https://github.com/Slimefun/Slimefun4/pull/3224 but accidentally touched an import so recreating the PR

Fixed ender lump guide entry

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/MetricsService.java

We used REPO_NAME in quite a few places which I didn't expect but here we are. Anyway, this fixes that.

Fix metrics not being able to download

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java

As of now, the AutoEnchanters blindly apply whatever is on the enchanted book onto the item, disregarding any check other than compatibility ones.
A small discussion on the Discord lead to two main ideas: some people like the fact everything gets overridden, meaning an extra layer of difficulty is added as more thought and planning has to be put in instead of blindly slapping books on the item. On the other hand, some people like the idea of the enchanter not completely disregarding what is on the item to begin with, and it to be able to only update the enchantments it needs to.
This PR is motivated by this dichotomy: an additional item setting has been added that allows servers to choose whether they do want the override or not (defaulting to yes so that the old behavior is conserved). …

Fixes #3248

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemFilter.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java

There are a lot of situations where SF items are CraftItemStacks not SlimefunItemStacks
This is most obvious with cargo and has been a big bottleneck there (~60%).
This PR addresses the cargo-specific point but will probably carry over to other parts of the code here and in addons.
In Cargo we wrap the items being used for comparison, these items can still be SF items just, they look like regular Bukkit items. So, the is item similar check should account for this.
With this change, it will check if it's wrapped and if it has item meta, if it does then it will try and get IDs to compare. Otherwise, fall back to the usual item meta comparison. This improves cargo performance by about 60% when filtering SF items.
The reason this change has such a big impact is simple, the display name code …

Improves item comparison performance

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/HerculesPickaxe.java

The Hercules' Pickaxe should function like Ore Crusher, so the drops of mining deepslate ores or copper ores should be their corresponding dusts.
Add support for Hercules' Pickaxe with 1.17 deepslate ores and copper ores.
Resolves #3251

Hercules' Pickaxe supports 1.17 deepslate ores and copper

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/package-info.java
src/main/resources/languages/en/messages.yml
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSmithingTableListener.java

The Smithing Table currently allows SlimefunItems to be used as the material (currently only Netherite). Given netherite is a nice looking martial for other possible items, this can allow very early access to Netherite tools unintentionally. The current examples are Zamak 1, 2 and 3 in SimpleStorage and Void Ingots in InfintyExpansion. 
New listener to deny SlimefunItems being used in the material slot. I have not modified the behavior to upgrade SlimefunItem tools from Diamond to Netherite asuming this is current both known and intended.
Tests for all 9 possible combinations of SlimefunItem, ItemStack and VanillaItem added
Resolves https://github.com/Sefiraat/Simple-Storage/issues/8

Smithing table listener

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/SolarGenerator.java

All of the generators in Slimefun have a default capacity BUT the ability to change it, with some having it >0 by default and thus effectively also working as an energy buffer. Solar Generators, on the otherhand, had no way to do this as the capacity was hardcoded to be 0 and unchangeable. This PR increases solar gens extensibility, by making it comparable to the other generators.
- Added a capacity member to Solar Generators
- Added capacity as a constructor parameter
- Added a constructor defaulting to the old behavior so nothing breaks
- Changed getCapacity() to return this new member instead of the hardcoded 0
N/A

Added ability to set capacity for Solar Gens, like all other gens

---

CHANGELOG.md
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/SolarGenerator.java

#3288 was nice but SolarGenerators override the isChargeable method for no reason. This actually breaks the creation of solar gens with a capacity because the child method is called and that returns false no matter what.
Since the method is actually useless (the super method checks the actual capacity) I have removed it
- Removed useless override of isChargeable
- Updated changelog
N/A

Removed useless overriding

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/ExplosiveBow.java

As the code is now, the Explosive Bow seems to work fine as long as there is enough distance from the impact point and nearby entities, especially if they are on the same level. When shooting an entity from close by though, especially if directly above, you get shot in the air even 40-60 blocks up which is definitely not supposed to happen.
- Cleaned up the extra redundant calculations
- Modified knockback calculation to achieve reasonable pushes
N/A

Fix explosive bow knockback being way too high if close to the entity

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java

Add a feature that if you shift left click in the Cheat guide, that it will give you a stack of that item instead of 1 (while respecting max stack size of an item).
- Add check for shift clicking while in Cheat menu

Add Shift Click in Cheat Menu

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/Parachute.java

right now, regardless of what recipetype you construct parachute with, it will always be enhanced crafting table
this fixes that
make parachute respect the constructor parameter
N/A

make parachute class respect constructor recipetype parameter

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java

All androids had a hardcoded check for minimum world height, to prevent them from moving above or below the world limit if the destination block is empty (always true above, may be true if bedrock has been removed below). This PR addresses this lower bound by making it compatible to 1.18 adding negative Y levels.
Resolves #3385

Fixes #3385

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/TimingsCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SummaryOrderType.java

am i allowed to do this
future-proofing
use a switch statement for SummaryOrderType

switch statement for SummaryOrderType

---

src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMapParser.java

The reason behind my changes is that I need to use the isLenient flag in order to load all valid biomes from my _editable_ biomemap file without the process being stopped by an exception. After that, missing (unconfigured) biomes would be used with a default value.
- Made BiomeMapParser class public
- Added a new fromJson method to BiomeMap class with the isLenient parameter

Ability to use isLenient flag of BiomeMapParser

---

src/main/resources/tags/dirt_variants.json

added rooted dirt to fix issue  #3469
might be smart to add #minecraft:shovel to the explosive shovel aswell this tag has been added since 1.17.
Rooted dirt has been added in 1.16 so that still doesnt solve the issue.
added rooted dirt to fix issue  #3469
Resolves  #3469

added rooted dirt to dirt variants

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java

A small bug fix for the ancient pedestal when retrieving placed items.
- Drop item instead if the player's inventory is full and no remaining stack space when retrieving the item back from the pedestal
- Resolves #3476

Fix pedestal item disappearing

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java

Fixes the small bug from advanced industrial miner during warm-up phase, it should respect the ```#stop()``` boolean value if there are any errors during ```#setPistonState``` validation, created a new branch with this pr.
- Prevent industrial miner from consuming fluid fuels if there are any error messages during ```#setPistonState```
- Resolves #3336

Industrial miner unintentional fuel consuming fix

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/machines/MachineProcessor.java

We found this issue by accident, but it seems that if Slimefun's ticks are faster than expected, Tier 3 items such as Electric Ore Grinders will produce an ArithmeticException.
https://pastebin.com/ZGWDJyWn - the error from our fork, this small patch fixed it.
Don't update the progress bar if the operation is already finished
Resolves #3538

Fix Arithmetic Error

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/items/ItemGroup.java

Currently when an addon adds an item to another addon's ItemGroup, a warning is thrown to the console. This allows addons to allow this behaviour if they want to (defaulted to current behaviour) so the warnings will not be triggered. This doesn't strictly change the behaviour of the items being added as this check didn't actually stop the items being added.
A boolean that can be set to disable the warning. Defaults to false.

Allow addons to disable warning

---

.github/workflows/auto-approve.yml
.github/workflows/json-validator.yml
.github/workflows/maven-compiler.yml
.github/workflows/sonarcloud.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/UnlockableItemStack.java
src/main/resources/languages/en/messages.yml

A newer and improved version of #2912 (Implemented suggestion 972, offers the ability to unlock items within the recipe book)
With the ability to translate strings related to it
https://youtu.be/wtYmTkPmMlc

Unlock researches in recipe view

---

src/main/java/io/github/thebusybiscuit/slimefun4/utils/itemstack/ColoredFireworkStar.java

I was using Firework Stars in my Addon and Realized that the Slimefun Runes that use Firework Stars still have the "Burst" & "Custom" Lore Lines. This is super simple and just makes that disappear for anything using the ColoredFireworkStar Class.
Adds the Hide Potion Effects Item Flag, just 1 line for the import, and 1 line for the Flag

Remove "Burst"  & "Custom" from Lore

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java

The dusts in the resources tab do not have the same order as their respective ingots
Moving the code for the silver dust to above the code for the lead dust, essentially swapping their positions

"Fixing" Dust Order

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java

(Idea from @J3fftw1 )
Since CS-CoreLib is no longer needed, and will cause issues to some addons, we should disable Slimefun and let users remove CS-CoreLib in order to run Slimefun and addons properly.
Change the CS-CoreLib warning level to severe.
Disable Slimefun when CS-CoreLib is installed.

Disable Slimefun when CS-CoreLib is installed

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java

I am making this pull request to add 3 API methods to the EnergyNet class.
This would allow either Core Slimefun or Addons to access what is a part of a given energy network allowing for the addition of multiple approved suggestions as well as QOL additions.
Added three getter methods that return an unmodifiable version of the three custom Maps available in the EnergyNet class. Those being, getGenerators, getCapacitors, getConsumers.
Fixed a typo in the java docs.
Annotated getId to be Nonnull as it was not already
There are no Related issues however these API changes can be used to implement, for example, https://discord.com/channels/565557184348422174/627048923122499584/1068050940294340608

Add API Methods to EnergyNet

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java

Added bamboo as a fuel type for androids
We might wanna change this again when 1.20 releases since all the new types of bamboo blocks.
Also do we wanna include all other burnable material since there is a huge list?
Added bamboo as a fuel type for androids

Added bamboo as a fuel type for androids

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java
src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java

As a player it can get really frustrating when all of your energy just gets voided due to overflow and if someone somehow achieves underflow that would be free energy which we do not want.
Added NumberUtils#limitedAddition()
Added NumberUtils#flowSafeAddition() and change the corresponding += and -= to use that method
Resolves #3758

Fix Energy Nets Over&Underflowing

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java

Adds a new recipe to convert 2 basalt into one blackstone (useful for nether only players)
New recipe to the grindstone
[Discord suggestion 2007](https://discord.com/channels/565557184348422174/627048923122499584/993741632878940260)

Add Basalt->Blackstone recipe

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java

During periods of server lag, an android may no longer be where it was previously after a move was made for any reason. This prevents the task that runs on a later tick from setting the skin of the Android and causes a console error. This change wraps a check around the setSkin in the same way as Capacitor skin updating does.
Potentially could include the conversion from base64 inside the check to save some CPU in the very rare case that the Android is not actually there.
Check if the android is actually still at the block location before trying to set a skin on it.
Resolves #3443

Fix android move task

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/KnowledgeFlask.java

Prevent flask of knowledge from able to fill up water which can turn the flask to a water bottle instead
Since the event cancellation is only registered for the flask as an item handler, I don't see this specific cancellation to affect other items while right clicking
- Moved the cancel event method outside of the condition
- Resolves #3524

Higher level interact event cancellation to prevent flask of knowledge from able to fill up water

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/SoulboundRune.java

Updated soulbound rune to respect vanilla getPickupDelay() value
added a check to ensure item can be picked up by players before the soulbound code converts the item.
resolves #3657

Update soulbound rune to respect itemPickupDelay()

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/EnchantedItem.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/FireStaff.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java

To make the Elemental Staff - Fire not disenchantable by default.
Creation of a Slimefun item class and altering the item setup to use this class.
This won't work with existing `Items.yml` so existing servers need to edit the file to reflect this change.
Resolves #3768

Make Fire Staff not disenchantable by default

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AbstractEnchantmentMachine.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java

This pr adds a way to sets a limit of how many enchants can go on an item.
Default is false
Default of the max enchants when its enabled is 10.
Added an item setting that checks for a limit on how many enchants can go on an item.
Resolves #3447

added a way to set max enchants to go on an item

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/LumberAxe.java

Only activate the Lumber Axe when the player is crouching. (similar to explosivetools)
Add a crouch check in the LumberAxe
[Discord issue 1515](https://discord.com/channels/565557184348422174/627048923122499584/892393743133577287)

Check if player is crouching

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AbstractEnchantmentMachine.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java

PR #3749 Introduced a bug in which normal enchanter/disenchanter behaviour would no longer function as expected. 
This PR changes the behaviour to work correctly both when the config option is on and off.
It also resolves an uncaught typo in the configuration item name as well as does a quick check to combine the total enchants from the target and the incumbent.
Resolves #3846

Change typo and logic issues with Enchant Amount problems

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

A recent merge resulted in an incorrect return if the block being broken was NOT a Slimefun item resulting in tool handlers no longer being called.
Change the logic to fire the event ONLY if the Slimefun block exists and then returning within that if statement only.

Fix incorrect return in BlockListener

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java

Saw #3432 and wanted to implement changes based on TheBusyBiscuit's line of thinking
Adds two new methods in `BlockStorage` 
- `void clearAllBlockInfoAtChunk(Chunk chunk, boolean destroy)`
- `void clearAllBlockInfoAtChunk(World world, int chunkX, int chunkZ, boolean destroy)`
Adds two new methods in `TickerTask`
- `void queueDelete(Collection<Location> locations, boolean destroy)`
- `void queueDelete(Map<Location, Boolean> locations)`
Given that both `BlockStorage` and `TickerTask` are going to be rewritten anyway, I haven't added any more convenience methods that I otherwise could for bulk operations. 
In summary, the changes allow the caller to perform a bulk version of `clearBlockInfo` for locations in a specific chunk. I'm not sure how much this will reduce hitting locks within the …

Add new methods in BlockStorage and TickerTask for clearing all block info in a chunk

---

src/main/resources/languages/translators.json

Fixes this error:
```
[23.06 19:06:06] [Server] [ERROR] [dough: skins] Exception while requesting skin: https://api.mojang.com/users/profiles/minecraft/amarcais53
[23.06 19:06:06] [Server] [WARN] [Slimefun] Attempted to refresh skin cache, got this response: ExecutionException: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/amarcais53
```
https://discord.com/channels/565557184348422174/565569196218384385/1121875045308969071
Renames amarcais53 to HamtaBot in the translators file
_None_

Rename amarcais53 to HamtaBot

---

.github/workflows/pr-labels.yml

Previously, the workflow did not have the proper perms since it was running from the fork for external contributors. With the `pull_request_target` event, we resolve this.
Ref: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
Security ref: https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests
Change the event from `pull_request` -> `pull_request_target`
N/A

Fix PR labels action perms

---

.github/workflows/preview-builds.yml

Apparently, download-artifact just checks the current workflow for it and not the run.
In our run-script, let's download the artifact as well. We know this is picking up the PR correctly: https://github.com/Slimefun/Slimefun4/actions/runs/5364131229/jobs/9732129940
So... this should work
N/A

Download artifact by ID, it isn't available in the workflow_run

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/PermissionsService.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java

Fixes a compatibility error introduced in the sound system pr's. 
The setHeader method does not exist in 1.16, so I am reverting it to use the deprecated method.
Revert the changes that changed `header` to `setHeader`
No github issues yet

Revert header changes

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java

Fixed 1.16.5 compat
This has been tested e2e on 1.16.5 paper
#parseComments does not exist on 1.16.5 so changed to the deprecated #copyHeader.
N/A

Fixed 1.16 compat

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java

If server owners disable specific items it can end up shifting multiblock recipes leading to either minimal or disasterous consequences. This PR aims to solve that.
Inside of MultiBlockMachine#load, instead of looping through each itemstack individually (input and output indiviudally), it now handles input and output at the same time. And checks if both are not disabled before adding both to the recipes. Previously it just went through stack at a time, so if an input was disabled the output would become the input and the next recipes input would be come the output. Now if either the input or output are disabled, neither item gets added which stops the shifting.
Resolves #3286

Fix Disabled Items Shifting Multiblock Recipes

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/LongFallBoots.java

The sound system made a breaking change to LongFallBoots causing FoxyMachines to no longer start.
Re-add the old constructor and deprecate.
https://github.com/GallowsDove/FoxyMachines/issues/71

Fix breaking change in LongFallBoots

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java

Quick fix to fix a bug introduced with the sound system changes
move the handle crafted output back to the else clause it was originally in before the sound system
No related issues, reported on discord

Fix Compressor doubling output

---

.github/workflows/maven-compiler.yml
.github/workflows/preview-builds.yml
.github/workflows/pull-request.yml

Changes the version in preview builds from `4.9-UNOFFICIAL` to `Preview Build #<pr-num>-<hash>`
Just a nice way to see what preview build we're running, check it's latest, check it's the right pr, etc.
Also does some cleanup, we no longer do preview stuff in the "Java CI" workflow and try to work around it firing on both push + pr. There's now just a PR workflow

Cleanup and add version to preview builds

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java

JavaDocs are currently broken and have been for a year :( 
The current error being spat out is due to this & (HTML y'all)
Latest job error: https://github.com/Slimefun/javadocs/actions/runs/5496270000/jobs/10016191730
Replace the & with the HTML entity for it.
N/A

possibly fix javadocs

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/SolarHelmetTask.java
src/main/resources/config.yml
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/items/TestSlimefunItem.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestCargoNodeListener.java

This PR will remove backwards compatiblity mode.
This will be a start of removing old crap to clean up Slimefun code and make new code more sustainable.
Only 2% (58 servers of the 2301 servers) of servers use backwards compatiblity mode. Where i dont think they know they have it on or have given it a thought. We also recommend in our optimizations guide to turn this feature of.
This should speed up those older servers severaly as well.
I havent benchedmarked this at all
Removed unused imports
Deleted backwards compatiblity mode
Deleted test regarded backwards compatiblity mode
Bit of Summer cleaning on my touched files

Removed backwards compatiblity mode

---

.github/workflows/merge-conflicts.yml

Currently forks get annoying and useless emails/workflow failures due to the merge-conflicts workflow.
See: <https://github.com/Sefiraat/Slimefun4/actions/runs/5501235305/jobs/10024683718>
Simply don't allow it to run on forks. Unsure if this will/could have detrimental effects?

Stop errors on forks

---

src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java

We're currently getting our ImmutableMap clone in clearAllBlockInfoAtChunk, instead we can _unsafely_ get the storage and save the overhead of duplicating the map (which for large servers is _massive_).
Right now it's taking basically all of the compute time:
Unsafely get the raw storage instead of our safe ImmutableMap.
Resolves #3432

Improve performance of clearAllBlockInfoAtChunk, don't get immutable map

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java

This PR fixes a possible duplication of custom enchantments due to inconsistencies in the `removeEnchantment` method of class `ItemStack` between Spigot and Paper due to [Paper Server Patch 0069](https://github.com/PaperMC/Paper/blob/b1696788d61ddc338bd2e61fac3b43ff60c432e1/patches/server/0069-Handle-Item-Meta-Inconsistencies.patch#L111C25-L111C25).
_Has been tested on Spigot and Paper 1.19.2 only._
Changed to method `removeEnchant` of class `ItemMeta` from the method `removeEnchantment` of class `ItemStack`, by also moving the `item.setItemMeta(itemMeta)` after the for loop.
Added a check and logger in hopes to prevent future enchantment duplication.
Resolves #3837

Fix possible custom enchantment duplication

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java

To fix the various problems people can encounter with the ancient pedestal, this is my re-write of #3637 
- Added ArmorStandUtils.java
- Added ArmorStandUtils#createArmorStand
- HologramProjector now uses ArmorStandUtils#createArmorStand
- Ancient Pedestal now implements NotHopperable
- Ancient Pedestal now uses ArmorStandUtils#createArmorStand to create an invisible armorstand, and sets the item as its passenger to prevent it from being moved by things like fluids and falling blocks
- Marked the item for an ancient pedestal be Invulnerable & UnlimitedLifeTime (To fix items despawning and making players loose their items)
Resolves #2940 
Resolves #3147
Resolves #3444
Resolves #3507

Ancient Pedestal Fixes

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricGoldPan.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AutomatedPanningMachine.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GoldPan.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/NetherGoldPan.java

I'm making this PR to supersede #3269, this has all of svr333's changes + merge conflict fixes & other changes I realized could (and some should) be made when fixing the merge conflicts.
- Fix various typos in the Javadocs of  `ElectricGoldPan`
- Changes `GoldPan` & `NetherGoldPan` to use a `Set<Material>` for Inputs, rather than just one material
- Changes `GoldPan#getInputMaterial` to `GoldPan#getInputMaterials`
- Changes `GoldPan#getDisplayRecipes` to use a `ArrayList` instead of a `LinkedList`
- Adds `GoldPan#isValidInputMaterial`
- Adds `GoldPan#isValidInput`
- Adds missing `@Nonnull` annotations to various methods
- Adds Javadocs to `GoldPan#getGoldPanDrops`
[Discord Suggestion #1614](https://discord.com/channels/565557184348422174/627048923122499584/887054754092580936)

Gold Pan Rework (Continuation of #3269)

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java

Making this PR to remove a version dependent method that was missed with the ancient altar fix PR
Resolves #3922

Patch for #3922

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GrapplingHook.java

When the grappling hook bat died, the lead was dropped.
Make the bat invulnerable.
Other changes:
replaced invisibility potion effect with ``setInvisible(true)``
replaced ``!isPresent()`` with ``isEmpty()``
Resolves #2352

fixed grappling hook not working due to bat dying

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/operations/CraftingOperation.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java

- Adjust ticker execution steps based on custom-ticker-delay changes
This PR adjust the tick rate based on the config value for custom-ticker-delay.
It will try to keep the tickers execution at a similar speed as to when the default value is used.
I also adjust the displayed time based on the difference of execution time.
Changed CraftingOperation to take into account the new ticks config. Normalize the value to the default one of one operation per 10 ticks. 
Changed NumberUtils. Added logic that calculates the time new changes will take to finish the operation.
Not sure if there is na issue open.
Here is how to reproduce the issue:
1. Adjust custom-ticker-delay to 20.
2. Run a ticker ingame.
3. The display timer will be wrong the execution slows down by 1/2 so the secounds and minutes …

- Adjust ticker times to show correct time on config changes for custom-ticker-delay

---

src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java

When using the gold pan with orebfuscator it doesn't update the obfuscated blocks
Add an event handler for the gold pan to ``OrebfuscatorIntegration.java`` that deobfuscates the blocks
Resolves #3764

Deobfuscate blocks when gold panning

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java

When an item is disabled you can't research it. This means you will never be able to gain 100% research completion on ``/sf stats``.
Add a filter to the researches that are required for 100% to only count the ones with at least 1 enabled item.
Resolves #3782
Related PR #3827

Add filter to researches for sf stats completion calculation

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java

for basic, advanced and carbonado gps transmitters there is a pattern in the values
the multiplier follows ``previous tier * 4`` (1 -> 4 -> 16)
the bonus follows ``previous tier * 4 + 100`` (0 -> 100 -> 500)
the power consumption per blockticker tick follows ``previous tier * 4 - 1`` (1 -> 3 -> 11)
but for the energized gps transmitter this pattern mostly breaks
the multiplier follows the pattern and becomes 64 ``previous tier * 4``
however the bonus becomes 600 ``previous tier + 100``
and the power consumption becomes 46 ``previous tier * 4 + 2``
this means if you compare the 4 carbonado transmitters it takes to craft the energized to the energized, you would be better off with 4 carbonado transmitters rather than 1 energized.
the added complexity for 4 carbonado transmitters is ``4 * (y …

Change Energized GPS Transmitter values to follow the pattern of previous tiers

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/SoulboundRune.java

Soulbound Runes can work properly.
In #3659 , `itemPickupDelay()`have been changed 'to ensure item can be picked up by players before the soulbound code converts the item'.
However, it produced another problem. In some Minecraft server core, Spigot for example, `Item.getPickupDelay()` (which was added in #3659 ) can return NEGATIVE values to show that the item is able to be picked up.
As a result, In some server, Soulbound Runes seldom work properly, distinct from other servers.
So i make a small change to fix it.
Resolves #3876 
- [I I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

Fix Soulbound Runes not working 

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java

In update 1.20 we havent add new log variants to android woodcutter, so I added one now.
Add cherry log to android woodcutter
Fixes #3913

Add cherry log to android woodcutter (Fixes #3913)

---

pom.xml

Updates dough to version d3b0997226, this fixes HuskTowns breaking Slimefun4 functionality.
After discovering the hook for HuskTowns was out of date in dough causing Slimefun multiblocks to not function, @NCBPFluffyBear fixed that issue, thus this needs updated to support those changes.
Just a dough version bump.
Resolves protection issues causing multiblocks and machines to not function. No issue report was opened.

Update pom.xml to use latest dough commit

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

The ``PlaceBlockEvent`` was logging block breaks
change ``Interaction.BREAK_BLOCK`` to ``Interaction.PLACE_BLOCK``
N/A

change BREAK_BLOCK to PLACE_BLOCK in BlockPlaceEvent

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java

Couldn't craft soulbound backpack with a woven backpack that had been assigned an id because of distinctive item check.
Add ``isItemSimilar`` parameters to ``MagicWorkbench::isCraftable`` to match ``EnchancedCraftingTable::isCraftable``
Resolves #3939

Fix unable to craft soulbound backpack with woven backpack with id

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

Elevator Plate needs another blocks below it.
So when the blocks below it destroyed by explosive pickaxe it will drop a vanilla stone pressure plate.
Placing a block on destroyed Elevator Plate will give back the elevator plate.
Add an ``EventHandler`` in ``BlockListener.java`` for ``ExplosiveToolBreakBlocksEvent`` to make use of the existing ``checkForSensitiveBlockAbove`` method. I made some changes to the method signature the make it compatible with the new event and also took the chance to fix the wrong ``@param`` tags that were there.
Other things: removed spaces on empty line and replaced ``addAll`` with parameterized constructor call.
Resolves #3009

correctly handle sensitive blocks above blocks broken with explosive tool

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/RadiationTask.java

There were 3 cases where you would get radiated when you weren't supposed to. The first case was when joining and having radioactive materials in your inventory. The radiation task would run before the armor task, meaning the radiation task would think you weren't wearing protective gear. The second case was ``hasFullProtectionAgainst`` returning false is some cases where it was supposed to return true. Example: infinity leggings with hazmat boots. The third case was when you were exposed to radiation, then put on protective armor, the exposure would stay. Meaning that when you would take your armor of you would get radiated again, even if you hadn't had radioactive materials in your inventory for a while.
1. Cache armor on join
2. Rewrite ``hasFullProtectionAgainst`` to actually work …

fix getting radiated when not supposed to

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
src/main/java/io/github/thebusybiscuit/slimefun4/integrations/IntegrationsManager.java

This PR resolves a duplication glitch with the Items adder plugin and Slimefun.
Disable blockbreak when its a custom block from items adder.
Resolves #3836

Fixes duplication glitch with explosive tools in combination with itemsadder

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/geo/ResourceManager.java

``OptionalInt.orElse`` evaluates the result even when the optional is present.
replace ``orElse`` with ``orElseGet`` (which doesn't evaluate if the optional is present).
Resolves #3974

fix generating geo resources every scan

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

I you broke a Slimefun block with a not unlocked item the contents of the inventory of the block would still drop. This is because the block handler would still get called no matter the results of the tool handler.
Move the tool handler code outside of the ``if (!e.isCancelled())`` block. That way if the tool handler cancels the event, the block handler won't get called. This should have no side effects since ``ignoreCancelled`` is true and there is nothing that cancels the event above the changed code.
https://discord.com/channels/565557184348422174/565569196218384385/1153792378327535738

fix breaking sf block with not unlocked item duping contents

---

pom.xml

This fixes the 1.20.2 compatibility
Big thanks to Jeff
Update dough to the latest version
Resolves #3986

updated dough version

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/MultiBlockCraftEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AbstractSmeltery.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AutomatedPanningMachine.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Juicer.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreWasher.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/PressureChamber.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/TableSaw.java

Making this PR to resolve the Merge Conflicts of #3439 and change some aspects of the PR
- Added `MultiBlockCraftEvent` an event called whenever a player uses a core slimefun multiblock to craft something
- It is cancellable and provides the listener with the player, machine, inputs and output
- a listener can also set the output if they so desire
- Changed all relevant classes to use `MultiBlockCraftEvent`
N/A

Add MultiBlockCraftEvent (Updated version of #3439)

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunGuideListener.java

When using the Slimefun Guide it does isItemSimilar and it respects lore, this was most likely due to the backwards compatibility and is since no longer needed. By removing the lore check we allow for any runes (core or addon) to work on the guide without breaking it, e.g. Soulbound (Core), Fireproof (Addon)
- No longer check lore in `SlimefunGuideListener#tryOpenGuide` 
N/A (I think)
- [] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

Remove Lore Check from Slimefun Guide

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/BookBinder.java

The bookbinder used to accept any book and just reset any level higher that the configured max back to the max.
For example protection 10 + protection 10 = protection 4
If any of the books contains an enchantment level higher than the configured max: don't consume the items
If the output would be the same any of the inputs: don't consume the items
Resolves #3247

don't consume bookbinder inputs if the output is worse than the input

---

.github/workflows/e2e-testing.yml
.github/workflows/pull-request.yml

We want to start putting more velocity into PRs, this means we also want more validation around the PRs we want to merge in.
Unit tests are good but can't catch everything, they can all pass but the plugin fails to start for XYZ reason. Therefore, we want to start adding some e2e tests for these cases where unit tests cannot provide the validation we want.
Adds a new workflow to test all supported MC versions (+ Java versions) in a live server environment.
This uses a new "e2e-tester" tool which is currently private within the org but will soon be open.

E2E testing

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
src/main/resources/languages/en/messages.yml
src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockBreakEvent.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockPlaceEvent.java
src/test/java/io/github/thebusybiscuit/slimefun4/test/TestUtilities.java

When breaking/placing blocks too quickly you can place a block and have the BlockStorage data subsequently removed resulting in loss of items. This has also caused fringe cases of blocks with multiple BlockMenus, ghost blocks and other oddities.
If a block is placed and the location is still queued for deletion, deny the block placement with a message to the player to let them know why it was denied.
This is a bit of a patch job, but a true resolution would be part of the BlockStorage rewrite and I feel is important enough to warrant a fix prior to that to ease server owners burdens.
Tested on 1.19.4 and no issues, worked as intended. But given the scope of potential effects community testing here would be wonderful :)

Deny placement when deletion is queued

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/UpdaterService.java
src/test/java/io/github/thebusybiscuit/slimefun4/core/services/TestUpdaterService.java

This PR replaces the broken builds page with https://blob.build
This is a new builds page build by @WalshyDev https://github.com/WalshyDev/blob-builds
In @WalshyDev fork there is a auto updater which automatically pulls the current changes and pushes it to the build page since it requires an api key.
We cant add an API key here only Cookie can
This PR is blocked till https://github.com/Slimefun/Slimefun4/pull/4027 is merged
Change from Cookies build page to Walshys build page
Resolves builds not being build

replace builds page with blob builds

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/researches/Research.java

When you first researched an item then disabled it you would still have the research. Sf stats however doesn't count researches without any enabled items for the total amount of researches. This means you could have more researches unlocked then the 'total'. This resulted in a fraction >1, thus an index >= titels.size, thus throwing an ``IndexOutOfBounds`` exception.
Also filter the unlocked researches of the player to only include researches with at least 1 enabled item.
Resolved #3995

Filter unlocked researches of player

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/SwordOfBeheading.java

According to Minecraft wiki [Head](https://minecraft.fandom.com/wiki/Head) page, piglin head is available but there is no way to get it through Sword of Beheading. I think it should drop a piglin head when killing a piglin.
- Use enhanced switch.
- Add piglin head as drop when killing piglins.
N/A

Allow sword of beheading drop piglin heads

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSmithingTableListener.java

Result slot moved so need to check version for correct slot.
Make result slot adapt based on minecraft version.
Also rewrote ``SmithingTableListener`` to be similar to ``CraftingTableListener``.
``SmithItemEvent`` and ``PrepareSmithingEvent`` exist in 1.16.
Resolves #3975

Add compatibility for the 1.20 smithing table

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/debug/Debug.java

``Debug::formatMessage`` doesn't work when ``vars[idx]`` cointains a ``{``
``msg.indexOf('{', i)`` will find the ``{`` that was just substituted in
replacing ``idx++;`` with ``i += ("" + vars[idx++]).length();`` should resolve this, because ``i`` will be moved to after anything that was just substituted in.

skip already substituted parts when formatting message

---

pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubTask.java

This PR updates dough which includes a fix for ratelimiting issues we are having in Slimefun.
Instead of hiting the MC api constantly we use a third-party with aggressive caching (`playerdb.co`).
update dough https://github.com/baked-libs/dough/pull/217
apparently there is no open issue about this.

fix rate limiting issues

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

When you would break a Slimefun block any sensitive blocks attached to it would be destroyed, but not drop their item.
This fix only works for 1.19+, but that accounts for 4/5 of all Slimefun servers. Feel free to suggest a 1.16-1.18 version.
Recursively check all attached sensitive blocks and drop them if they should be, while respecting ``max-chained-neighbor-updates`` in ``server.properties``.
Resolves #3182 
Resolves #3831

Fix sensitive blocks attached to sf blocks not dropping (1.19+)

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
src/test/java/io/github/thebusybiscuit/slimefun4/core/guide/TestGuideOpening.java

To allow any servers that have colored chat to still use the slimefun search system
- In `SurvivalSlimefunGuide#openSearch` when `searchTerm` is defined I wrapped it with `ChatColor#stripColor`
- In `TestGuideOpening` I changed `testOpenSearch` to `testOpenSearchHistory` to better reflect the test
- In `TestGuideOpening` I created a new `testOpenSearch` method that tests with a normal, and then colored version of the same search. It opens the search for both and asserts that the item registered that should be found by the search is in the upper inventory (where the search would be displayed)
Resolves #4043

Strip colors from search term

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

A bug slipped through the craps on the sensitive blocks PR
gets and then re sets the block data of the block for sensitive blocks

Hotfix for the Sensistive Block Check

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

Fixing it is taking longer than expected so we should revert until we do get it done
removing all the changes with sensitive blocks
N/A

Revert Sensitive Block Changes

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

Sensitive blocks were an issue, they were "fixed" a couple of times (#3966, #4048) and then we reverted the changes as it was a mess (#4049).
This now solves the issue for good in terms of vanilla sensitive blocks.
Only drop items when BlockBreakEvent.isDropItems() is false, as otherwise we get double vanilla drops
Check around the block for sensitive blocks up until the max chained amount
Resolves #3182
Resolves #3831

Fixed vanilla sensitive blocks

---

pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubTask.java

In `GitHubTask` we're doing `Optional<String> skin = Optional.of(future.get().toString());` where `future.get()` returns `PlayerSkin`. However, `PlayerSkin` does not have a `toString()` function and therefore this was resulting in the normal Object#toString meaning `skin` was like `io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerSkin@abcdef123` instead of the base64 texture.
This PR updates dough and a small change in our contributor code to fix #4071 
Unfortunately, this change cannot be easily unit-tested as the whole `GitHubTask` is private and changing that wouldn't make sense. We could run the Runnable but we shouldn't, it'll do a bunch of network requests and generally just be bad practice to test a single function.
Dough PR for this change: …

Fix contributor head being pullable

---

.adr-dir
.gitignore
docs/adr/0001-storage-layer.md
docs/adr/README.md
src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/GPSNetwork.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/Waypoint.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerBackpack.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
src/main/java/io/github/thebusybiscuit/slimefun4/storage/Storage.java
src/main/java/io/github/thebusybiscuit/slimefun4/storage/backend/legacy/LegacyStorage.java
src/main/java/io/github/thebusybiscuit/slimefun4/storage/data/PlayerData.java
src/main/java/io/github/thebusybiscuit/slimefun4/storage/legacy/LegacyStorage.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/gps/TestWaypoints.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/profiles/TestPlayerBackpacks.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestBackpackListener.java
src/test/java/io/github/thebusybiscuit/slimefun4/storage/backend/TestLegacyBackend.java
src/test/java/io/github/thebusybiscuit/slimefun4/test/mocks/MockProfile.java

Ok... bear with me on this!
This PR is the start of our new storage layer. Famously known as the "BlockStorage rewrite" or "SQL for player data".
This PR goes over the goals, and how we get there and starts implementation of phase 1.
Please read through the whole ADR as that describes the goal that I'm going for here.
Please review and comment on the ADR as well as the code being done here.
This PR is mainly about kicking things off, sharing the direction/goal and starting the process. It is not about implementing the API, the additional backends or anything else. The API seen in this PR is a bare minimum and will change to be more inline with what we will probably go for going forward.
* Save and load the PlayerProfile with the new storage layer
* Move saving/loading outside of the …

Storage rewrite - Phase 1

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

This PR temporarily disables the senstive blocks check added in #4050.
This will now rebreak these issues https://github.com/Slimefun/Slimefun4/issues/3831 https://github.com/Slimefun/Slimefun4/issues/3182
commented out the code added in #4050

temporarily diable senstive blocks check

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/profiles/TestPlayerBackpacks.java

Fixes backpack IDs not incrementing unless the server is closed.
The ID increment code was still reading the config file, updated this to rely on PlayerData. Made the next ID now be the backpack size. Created a new test to validate behaviour.
Fixes #4080

Fix backpack IDs not incrementing

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemInteractListener.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/interfaces/InventoryBlock.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSlimefunItemInteractListener.java
src/test/java/io/github/thebusybiscuit/slimefun4/test/TestUtilities.java

Per #4087 if you can get into the inventory of a broken block you can easily dupe items (take them out of the inv before cleanup - 500ms by default and from block drops).
We want to fix that and there's also just some general cleanup
There are 2 parts to this fix, the first is disabling opening the inventory if the block is broken. The second is closing the inventory on block create (rather than an SF tick later). Created a pretty long test to validate this behaviour and fully verified it through debugger.
I also did a bit of cleanup, and commented out `checkForSensitiveBlocks` rather than the code in the function so we don't have random unused code. Moved @Nonnull annotations in BiomeMap as vscode was freaking out over it being in the middle of generics.
Fixes #4087

Fixes #4087 and some cleanup

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemInteractListener.java

Small bug in the latest change causes an NPE if interacting with air.
Add a null check before we check for pending deletion.
<https://paste.walshy.dev/IwsWtVpt568o>

Fixes NPE when interacting with air

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSlimefunItemInteractListener.java

Not all blocks will have an inventory, we missed a null check.
MockBukkit didn't catch as we can't check for viewers today :/
* Adds a null check to inventory closing in block break.
* Adds basic item interaction and basic block interaction tests
https://pastebin.com/UiCbddCm

Fix another bug with interaction fix and add more interaction tests

---

.gitignore
docs/sop/update.md
pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/FileUtils.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockPlaceEvent.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/gps/TestWaypoints.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestCargoNodeListener.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSlimefunGuideListener.java
src/test/java/io/github/thebusybiscuit/slimefun4/storage/backend/TestLegacyBackend.java
src/test/java/io/github/thebusybiscuit/slimefun4/test/TestUtilities.java

This PR updates mockbukkit.
It was a huge pain
Make main class not final
Changed dependency order(this apparently matters a lot. Dont ask me why)
Changed grass material to grass_block. in 1.20.4 grass isnt a thing anymore. We should be using grass only in mocks so this shouldnt effect anything

Update MockBukkit to 1.20.4 along with existing tests

---

src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java

This bug apparenttly has existed for 7 months.
On 1.19.4 you are not able to place items on an ancient altar you get the following error
https://pastebin.com/87UpB46w
revert https://github.com/Slimefun/Slimefun4/commit/060b59dd0f09886b72d0b4e63ab9f3d7ce5db952
issue reported on discord
https://canary.discord.com/channels/565557184348422174/565569196218384385/1196756895948619797

fix items not being able to be placed on ancient altar

---

pom.xml

Items currently won't stack due to random UUIDs being used on each load. This will fix that
Update dough to include pr https://github.com/baked-libs/dough/pull/246
Fixes #4097

Update dough to fix item stacking issue

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSlimefunItemInteractListener.java

when a slimefun block with an inventory has a viewer and gets broken it turns into a vanilla item.
Changed the for loop.
https://paste.walshy.dev/pS31PJ6GnlJy

fix slimefun block turning into a vanilla block if there are viewers

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunItemRegistryFinalizedEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunRegistryFinalizedEvent.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/PostSetup.java
src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java

This Event is provided so that plugins that have integrations with each other aren't stuck in a state in which some SlimefunItems may not be available to one plugin or the other.
I will use this event to provide a cleaner integration between Dynatech and other plugins. Currently InfinityXpansion, ExoticGarden, and Gastronomicon.
Make an event to be able to listen to Slimefun's Registry finalizing all static items.

:sparkles: feat(api): Introduce SlimefunItemRegistryFinalizedEvent

---

src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java

You might be having a deja vu.
This PR fixes Slimefun blocks turning into vanilla blocks on 1.20 and 1.20.1
add a different version check
#4103 
- [x I followed the existing code standards and didn't mess up the formatting.

fix slimefun blocks turning into vanilla blocks for 1.20.1 and lower

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java

Apparently when I made the original PR I accidentally didn't make this method static and none of the reviewers caught it XD
- Made `SlimefunItem#getOptionalByItem` `static`
N/A

Make SlimefunItem#getOptionalByItem static like intended

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/SlimefunTabCompleter.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/debug/TestCase.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/AutoSavingService.java

Moves the PlayerProfile saving off the main thread
Move PlayerProfile off main thread, add debugs and improve tab completion for debug
Moved the PlayerProfile saving off the main thread, we generally load this off-thread but now we also save off-thread. I thought we were already doing this but apparently not, especially with our current YAML stuff this should definitely be done
Also done a small change to ensure that we don't remove the PlayerProfile from memory if the player is still online. I don't think we ever had a reported issue from this but it's kinda weird behaviour
Finally, added some debug logs to the saving logic, this can be enabled with `/sf debug slimefun_player_profile_data`. Also added auto-complete to /sf debug because it's nice, this only works for Slimefun test cases …

Move PlayerProfile saving off the main thread

---

pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/UpdaterService.java

Adds a "Update available" to /sf versions if someone isn't on the latest Slimefun version. Hovering over will tell the user they should update and not to report bugs on this version.
Needs https://github.com/baked-libs/dough/pull/245 merged
Check if we're on the latest version in the versions command and if not, send a update available message.
N/A

Add update warning to /sf versions

---

pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/storage/backend/legacy/LegacyStorage.java
src/test/java/io/github/thebusybiscuit/slimefun4/storage/backend/TestLegacyBackend.java

Due to a logic bug in the Legacy storage backend if there was a duplicate ID it would mark it as researched for the first, then see it researched already and remove it on the second. This was happening for the Coal Generator and Bio Reactor here. Both shared he same research ID 173.
We're just doing this fix for now until we can move away from the legacy backend (work in progress).
If we already see the value as researched in the file just double-check that the player does not have it researched.
This change also needed us to pin Paper due to a Paper PR that caused MockBukkit to fail. Not a fan of this but it should only be temporary until MockBukkit updates.
I hate that we always use a "1.x" version which versions are pushed to... Everyone really should always pin to just specific …

Fixes #4123 - Coal Generator will no longer be locked after researching

---

src/main/java/io/github/thebusybiscuit/slimefun4/Threads.java
src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java

Fixes exhaustion when loading large PlayerProfiles due to multiple load calls being made.
If we're already loading the profile, we don't want to spin up a whole new thread and load the profile again/more. This can very easily cause CPU, memory and thread exhaustion if the profile is large
We saw AbstractArmorTask constantly try to get the PlayerProfile (every 10 mc ticks) even though the profile was still being loaded (due to it's very large size). This compounded the issue and ended up killing servers off entirely.
Add tracking for when we're loading the PlayerProfile from file into memory. If the profile is loading, we will simply return and not try to load it again. This does mean that callbacks for PlayerProfile#get are currently tossed away, this isn't ideal but IMO is acceptable …

Fixes exhaustion when loading large profiles

---

pom.xml

Fixes guide search when using colored chat
With https://github.com/baked-libs/dough/pull/250 handle the ChatInput as colored text rather than user friendly (&) text.
Also pinned Spigot to resolve build issues.
N/A

Fixes guide search when using colored chat

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java

This PR fixes a dupe glitch with backpacks. There was a race condition in PlayerProfile where the UUID got removed from the loading map before it was finished loading and inserted into the Registry. This meant that the PlayerProfile could load twice if someone did something like spam open a backpack after joining.
We now finish loading and adding to the registry before marking it as no longer loading.
Move where we finish loading (remove from the loading map) to ensure we're always after the registry.
Fixes #4130 
possibly fix for #4131

fix dupe glitch with backpacks

---

CHANGELOG.md
pom.xml

Update the changelog
Revert dependency update from maven-shade-plugin from 3.5.2 to 3.5.1. This made it so jitpack couldnt build due to maven-shade-plugin requring Maven version 3.6.3, jitpack runs 3.6.1.
Update the changelog
Revert dependency update from maven-shade-plugin from 3.5.2 to 3.5.1. This made it so jitpack couldnt build due to maven-shade-plugin requring Maven version 3.6.3, jitpack runs 3.6.1.
N/A

update changelog && revert dependency update

---

.github/workflows/publish-build.yml

We've moved to blob builds, let's finally get the auto-publish working
Adds a new workflow for publishing on pushes to master/stable.
N/A

[ci skip] Add blob builds workflow

---

pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/MetricsService.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/ContributionsConnector.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubActivityConnector.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubConnector.java
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubIssuesConnector.java

When we first implemented Unirest, the goal was always to remove it once we moved to Java 11 minimum. It's been a while since this happened so let's do this.
This reduces the jar size from 4.7 MB (4782834 bytes) to 2.4 MB (2480486 bytes) so we remove ~2.3 MB.
Removes Unirest with Java's native HttpClient (introduced in Java 11)
N/A

Remove Unirest and replace with Java's native HttpClient

---

.github/workflows/javadocs.yml
.gitignore
pom.xml
src/main/java/io/github/thebusybiscuit/slimefun4/core/services/ThreadService.java

The javadocs have again been broken for a while, I said I wanted to do this last time and forgot. So now, we're gonna both fix the docs and add validation to this repo.
* Adds a new workflow "Javadocs" to validate that we can build the javadocs and there are no errors
* Fixes the javadoc errors in ThreadService
* Changes the destination dir of the javadocs since we now have a real "docs" dir 
* Accompanying javadocs PR - https://github.com/Slimefun/javadocs/pull/14 
N/A

Fixes Javadocs build & adds workflow to ensure no more breakages

---

src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java

While adding tests to #3920 I pushed some tests which would never fail, this fixes them
Set a flag if the event failure is correctly caught. If not the test has actually failed, so we throw a new exception of our own.

Actually check if the negative tests do their job

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/MultiTool.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/MultiToolMode.java

Multi tools reset their mode after server restart. I found it really annoying and so did my players, so I decided to fix that.
This pull request also adds a display of current multi tool mode in its lore.
Feel free to improve my code. I tried to achieve my goal without changing too much stuff, so it *shouldn't* break anything.
- Multi tools keep their current mode after server restart
- Current multi tool mode is displayed in its lore (works with already existing multi tools)

Multi tools won't reset their modes after server restart

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/MultiTool.java

Fixed a bug introduced in PR #4122.
**Untested, but should be fine with only a small change.**
Set the default index to 0, as `PersistentDataAPI.getInt` returns -1 by default.
Fixes #4203

fix: fix the default index of Multitool modes

---

src/main/java/me/mrCookieSlime/CSCoreLibPlugin/Configuration/Config.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ClickAction.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/MenuListener.java
src/main/java/me/mrCookieSlime/CSCoreLibPlugin/package-info.java
src/main/java/me/mrCookieSlime/package-info.java

Undepreated the old stuff in `me.mrCookieSlime`. This was done because we have no replacement yet, and the IDE warnings are getting annoying in addons. Deprecate these *after* having a replacement.

Undeprecate the CS-Core stuff for now

---

src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java

I have a seperate system of managing recipes and would like a shorthand to not have to define them at item creation time. 
Add a `SlimefunItem` constructor that just passed RecipeType.NULL and empty recipe for its `recipe` and `input` fields.

Add a SlimefunItem constructor that only needs `ItemGroup` and `SlimefunItemStack`

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ChargingBench.java

Making ChargingBench rechargeable only ItemStacks with 1 items
By adding this feature addon makers can make heir own Rechargeable any item they want and not be limited to tools
Resolves  #4183

Fix ChargingBench

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java

Currently SF supports removing ghost blocks by placing a block where the "ghost block" is, however it only supports ghost blocks of registered items. If an item is no longer registered but the data is still there, it does not get removed. This just changes the ghost block handling to account for that as well.
Make the clearing require block info, not an sf item
Issue with Dynatech's new update

Remove block info if present when placing on air (more in desc)

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricSmeltery.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/ChestMenuUtils.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java

The same output handler is used in many parts of the code and it would be better to have a defaul handler
Add a default handler to the ChestMenuUtils, similar to the already existing `ChestMenuUtils#getEmptyClickHandler` method
https://sonarcloud.io/project/issues?open=AXTBL6ehIVI46B1gLWaW&id=Slimefun_Slimefun4

Reduce code duplication

---

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java

There is a typo in the file AGenerator.java. Its only in the warn, so its a simple and easy fix.
Replacing setEnergyCapacity with setCapacity.

Fix setCapacity typo in a warn of AGenerator.java

---

.github/workflows/e2e-testing.yml
src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestMinecraftVersion.java

- Fix `MinecraftVersion#isBefore(major, minor)`.
- Use `==` to compare base potion type, as it is enum.
- Added unit tests.
- Added more version to e2e testing workflow (1.20.4, 1.20.6), disabled the latest (1.21.1) for now.
Waiting for Boomer to test with a few addons.
Resolves issues in #4186.

chore: various changes to 1.20.5 branch

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/MetricsService.java

We didn't have a log line for this previously so it would say "failed to download" but not provide any further info. This provides that info
Log that we got a non-200 status code and log the code.
N/A

Log non-200 on metrics download

---

src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoBrewer.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/EnchantmentRune.java
src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ClimbingPick.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMapParser.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java
src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/TagParser.java

Removes usages of `EnumMap` and `EnumSet` on types which implement `Keyed`

Remove EnumMap and EnumSet usages

---

src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java

I don't like using Location so Im trying to move a lot of my stuff to`BlockPosition` instead. This helps ease that transition.
Add blockstorage helpers that use BlockPosition instead of `Location` and `Block`

Add simple BlockPosition based BlockStorage helpers. 

---

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java

Bugfix
* Replace the use of a `HashSet` with `ConcurrentHashMap#newKeySet` in the ticker task to prevent `CME`s from ocurring when we are ticking
* Updated relevant javadocs
* Replace getOrDefault creations of `HashSet` with `Collections#emptySet`
Fixes #3696

Use a thread-safe Set impl for the TickerTask's tickingLocations
