Slimefun/Slimefun4

SlimefunStartup.java
I fixed a bug that make players don't need to wear full hazmat suit when having a radioactive item in their inventory.
=> Fixed full hazmat suit necessity

src/me/mrCookieSlime/Slimefun/holograms/ArmorStandFactory.java
There, only changed one thing.
If you misunderstood me, 
i meant that the user does not have to be exposed to a stacktrace, 
when you only call this code from ONE place. .-.
=> Change reflection field to work on 1.10 - 1.10.2

src/config.yml, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutoDisenchanter.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
I saw a suggestion in the forum to add an option to the disenchanter which would prevent it from disenchanting Slimefun Gear (eg. 24-Carat Gold Armor, it has Unbreaking X), as it can be very overpowered.
=> Fixed 1 bug and added a new feature.

src/me/mrCookieSlime/Slimefun/Android/AndroidType.java, src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java, src/me/mrCookieSlime/Slimefun/Android/ScriptPart.java, src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunStartup.java
Allows the harvest of Exotic Garden plants
=> Added Advanced Farmer Android

src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
I also added a Nether Star Generator. It generates 720J/s. You also get a withering effect while being near it.
=> Made Reactor abstract

src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/HeatedPressureChamber.java, src/me/mrCookieSlime/Slimefun/Setup/MiscSetup.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java, src/me/mrCookieSlime/Slimefun/api/TickerTask.java, src/plugin.yml
=> Finished Nether Ice Coolant Cell production chain.

src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
=> Added researches

src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
Looks like tellraw doesn't support the & symbols, eh?
Don't mind the tiny mess I made. There could've been some improvements.
=> Book Mode Color Fix

src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
Reverts TheBusyBiscuit/Slimefun4#53
Did not need a fix
=> Revert "Book Mode Color Fix"

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Simple Fix. I thought this won't affect as much servers
=> Cargo Connected Text Color Doesn't work on a few servers.

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/ExcludedSoulboundTool.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/ExcludedTool.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java
Better Implementation. xD
Fix #74
=> Implemention of ExcludedTool and ExcludedSoulboundTool

src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java
There may be a better way of implementing this, but.... ehh.. this is my
concept :P.
The other lines, are just naughty github not accepting the Color code
symbols.
Fix Attempt for: https://github.com/TheBusyBiscuit/Slimefun4/issues/89
=> Off-Hand Monster Jerky Fix

src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java
Derp. Changed the Minecraft Color Code, and added PlayerInventory
update, as suggested by TheBusyBiscuit.
=> Minor Fixes

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/XPCollector.java
Fix the XP duplication bug with xp collectors. Fix #106
=> Fix XP Dupe Bug

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Fixed pickaxe to prevent duplication of ores.
=> Fix Pickaxe of Vein Mining Dupe

src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java
Fixes the item and places back in players inventory.
Issue was posted in: https://github.com/TheBusyBiscuit/Slimefun4/issues/229
=> Fixed Talisman of Anvil

src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java
Reverts TheBusyBiscuit/Slimefun4#252
=> Revert "Fixed Talisman of Anvil"

src/config.yml, src/me/mrCookieSlime/Slimefun/Objects/Research.java
Related to https://github.com/TheBusyBiscuit/Slimefun4/issues/308
=> Added option to toggle research fireworks

src/config.yml, src/me/mrCookieSlime/Slimefun/Objects/Research.java
Related to https://github.com/TheBusyBiscuit/Slimefun4/issues/308
=> Splited option to toggle fireworks into "when researched" & "when given"

src/me/mrCookieSlime/Slimefun/Commands/SlimefunCommand.java, src/me/mrCookieSlime/Slimefun/Setup/Messages.java
Related to https://github.com/TheBusyBiscuit/Slimefun4/issues/300
Also removed a useless online check, and adapted messages (may need the
owners to regenerate messages.yml file)
=> Added an optional amount parameter for /sf give

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutoDisenchanter.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutoEnchanter.java
Related to https://github.com/TheBusyBiscuit/Slimefun4/issues/280
=> Added option to toggle "enchantability" of an item

src/me/mrCookieSlime/Slimefun/Setup/Messages.java
This is a just a little tweak with color codes to avoid that :
=> Little color fixes in messages

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/me/mrCookieSlime/Slimefun/api/Slimefun.java
Related to https://github.com/TheBusyBiscuit/Slimefun4/pull/337,
https://github.com/TheBusyBiscuit/Slimefun4/issues/231
=> Added a State enum for SlimefunItem

src/me/mrCookieSlime/Slimefun/Objects/Research.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java, src/me/mrCookieSlime/Slimefun/SlimefunStartup.java
I documented the whole Research.java class (this is the beginning of the huge task of documenting about the whole Slimefun API ^^).
I also edited, renamed, and created some methods for Research. 
I'd also like to know if I can repush https://github.com/TheBusyBiscuit/Slimefun4/pull/70. It seems MySQL implementation has not begun yet.
=> Documented and improved Researches

src/me/mrCookieSlime/Slimefun/api/item_transport/CargoNet.java
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/363
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/161
=> Fixes a NumberFormatException when trying to read nonexistent frequency of a CargoManager

src/me/mrCookieSlime/Slimefun/SlimefunStartup.java, src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java
=> Fixes IllegalArgumentException caused by a mis-handled negative bound in randomizer

src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/380
=> Fixes Fortune V impossible to be obtained using Wizard Talisman

src/me/mrCookieSlime/Slimefun/SlimefunStartup.java
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/297
=> Fixed radioactive items giving effects even if they were disabled

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/338
Btw, when will you release 4.1.10 ?
=> Fixed IllegalArgumentException when try to push null item from a ReactorAccessPort

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/Alloy.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/EnderTalisman.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/VanillaItem.java, src/me/mrCookieSlime/Slimefun/Setup/WikiSetup.java, src/me/mrCookieSlime/Slimefun/api/Slimefun.java
Here is a new patch of documentation.
I've also edited some methods, privatized some fields.
Further documentation is ongoing, however this takes a lot of time.
=> Documentation - 1

src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/EnhancedFurnace.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/391
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/395
=> Blockstates must be explicitly updated as of 1.12.1

src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
Fixes TheBusyBiscuit/Slimefun4#195.
=> Don't consume XP until we are about to unlock the requested research.

src/me/mrCookieSlime/Slimefun/Commands/SlimefunTabCompleter.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
Fixed a typo and added the ability to complete words on tab completion smartly.
=> Minor fix and enhancement to tab completion

src/me/mrCookieSlime/Slimefun/api/TickerTask.java
Done to allow an easier reading of plugins in error reports in order to find the addons.
=> Error reports : prioritized Slimefun Environment (addons, etc)

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
A fix to the recipes of christmas items
=> Fix Christmas Cookie and Chocolate Milk Recipes

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/EnderTalisman.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/Talisman.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/listeners/ItemPickupListener.java, src/me/mrCookieSlime/Slimefun/listeners/ItemPickupListener_1_12.java, src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java, src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java
with minor API changes
fixes #367
=> Fix NPE on BlockBreakEvent with Smelter's Pickaxe

src/me/mrCookieSlime/Slimefun/Lists/RecipeType.java, src/me/mrCookieSlime/Slimefun/api/BlockStorage.java, src/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java, src/me/mrCookieSlime/Slimefun/api/inventory/UniversalBlockMenu.java, src/me/mrCookieSlime/Slimefun/api/machine/MachineConfig.java, src/me/mrCookieSlime/Slimefun/api/machine/MachineSettings.java, src/me/mrCookieSlime/Slimefun/listeners/AncientAltarListener.java, src/me/mrCookieSlime/Slimefun/listeners/AndroidKillingListener.java, src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java, src/me/mrCookieSlime/Slimefun/listeners/TeleporterListener.java, src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java
Changed getName to getID
And fixed some deprecations
=> Changed getName to getID and some deprecation fix

src/me/mrCookieSlime/Slimefun/api/item_transport/CargoManager.java
done by saving the blockinfo to avoid heavy calls. Would probably need later a more reliable "rewrite".
Fixes https://github.com/TheBusyBiscuit/Slimefun4/issues/514
=> Small performance improvement in CargoManager

src/config.yml, src/me/mrCookieSlime/Slimefun/Setup/Messages.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/listeners/AncientAltarListener.java
Now the pedestal drops the item which is currently above of it when it's broken.
Edit: Changed obstructed message + minor changes.
=> Fixed Pedestal not dropping item when is broken or explodes

src/me/mrCookieSlime/Slimefun/Lists/Categories.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
Just a minor fix and a minor change before I have a go on reworking the guide layout :)
=> Preparing new guide layout

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/EnhancedFurnace.java, src/me/mrCookieSlime/Slimefun/listeners/ClearLaggIntegration.java
Fixed an issue mentioned in #512  #453 #411
Happy new year.
=> Fixed speed modifier not getting applied to Enhanced Furnaces

src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason.java, src/me/mrCookieSlime/Slimefun/api/BlockStorage.java
=> Fixed Android Miner not breaking Slimefun blocks correctly

src/me/mrCookieSlime/Slimefun/AncientAltar/RitualAnimation.java
Tested on a recent spigot server, but have not tested thoroughly - is there an amount of testing that is desired?
=> Simplify the RitualAnimation

src/me/mrCookieSlime/Slimefun/api/TickerTask.java
Cleans up the source code a bit (although not much)
=> Simplify error file name generation

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricDustWasher.java
See the issue for description, similar to the fix in #503 except it has to work on output slots only.
=> Fix #617: Electric Dust Washer - Dust Choice.

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/api/BlockStorage.java, src/me/mrCookieSlime/Slimefun/api/TickerTask.java, src/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java
(Maybe) Fixes #509
It would be ideal for @itslukemango or @andris155 or anyone running Paper to check if this fixes it. It does not throw any exceptions on my Spigot testing, so it shouldn't cause issues on Paper.
=> Check if the chunk is loaded instead of relying on exceptions

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunStartup.java, src/me/mrCookieSlime/Slimefun/api/energy/EnergyNet.java, src/me/mrCookieSlime/Slimefun/api/item_transport/CargoNet.java, src/me/mrCookieSlime/Slimefun/api/network/Network.java, src/me/mrCookieSlime/Slimefun/listeners/NetworkListener.java
The diff is huge because a lot of whitespace got deleted from the end of lines, sorry.
I'll consider adding a linter to the repo to enforce style rules to stop the inconsistent whitespace behaviours. 
I am hoping to do some Cargo Network efficiency updates very soon, but thought I'd post this so you can review.
Shouldn't change functionality, but the cargo net visualizer currently does not show in the same way it did before, but that would be fixable with an upgrade to the base Network class in the near future.
=> Create a Network class to manage networks in a stateful way

src/me/mrCookieSlime/Slimefun/Commands/SlimefunCommand.java, src/me/mrCookieSlime/Slimefun/GPS/TeleportationSequence.java, src/me/mrCookieSlime/Slimefun/Lists/RecipeType.java, src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunStartup.java, src/me/mrCookieSlime/Slimefun/listeners/DamageListener.java, src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java, src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java
Added the kitchen recipe type for ExoticGarden.
Fixed colors while teleporting using the GPS.
Fixed using Wind Staff in Creative mode.
Allowed using different log types in the Saw Mill.
Added holidays prefixes for some items.
Replaced deprecated methods.
=> A small bunch of something

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Added CS-CoreLib permission check for Slimefun Machines.
Updated some deprecated methods.
=> Added CS-CoreLib permission check for Slimefun Machines

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java, src/me/mrCookieSlime/Slimefun/listeners/ItemPickupListener.java, src/me/mrCookieSlime/Slimefun/listeners/ItemPickupListener_1_12.java
Fix for #583 and also a tiny dupe glitch where players could break barrels on the saw mill and get both planks and the barrel back.
=> Updated saw mill protection check

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Also a few more .clones() were added as a precaution for the future.
=> Fixes soulbound backpack crafting

src/me/mrCookieSlime/Slimefun/AncientAltar/RitualAnimation.java, src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java, src/me/mrCookieSlime/Slimefun/Commands/SlimefunCommand.java, src/me/mrCookieSlime/Slimefun/GPS/Elevator.java, src/me/mrCookieSlime/Slimefun/Hashing/ItemHash.java, src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/me/mrCookieSlime/Slimefun/Objects/Category.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AdvancedCargoOutputNode.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutomatedCraftingChamber.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CargoCraftingNode.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CargoInputNode.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CargoOutputNode.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/WitherAssembler.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/XPCollector.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java, src/me/mrCookieSlime/Slimefun/SlimefunStartup.java, src/me/mrCookieSlime/Slimefun/api/BlockStorage.java, src/me/mrCookieSlime/Slimefun/api/TickerTask.java, src/me/mrCookieSlime/Slimefun/api/energy/ChargableBlock.java, src/me/mrCookieSlime/Slimefun/api/energy/EnergyNet.java, src/me/mrCookieSlime/Slimefun/api/item_transport/CargoManager.java, src/me/mrCookieSlime/Slimefun/api/item_transport/CargoNet.java, src/me/mrCookieSlime/Slimefun/api/network/Network.java, src/me/mrCookieSlime/Slimefun/holograms/Projector.java, src/me/mrCookieSlime/Slimefun/listeners/BlockListener.java, src/me/mrCookieSlime/Slimefun/listeners/ItemPickupListener.java, src/me/mrCookieSlime/Slimefun/listeners/TeleporterListener.java
• Allowed using LOG_2 in the walking sticks recipes.
• Fixed color codes when using book menu design.
• Replaced deprecated methods.
• Removed unused imports.
_P.S. @TheBusyBiscuit, sorry for the AReactor.java. I accidentally replaced spaces with tabs. I know that you don't like changes like that :)_
=> Some additions and fixes

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Current multi-block system can compare only materials of blocks, so I added manual checks for Solar Panels in MultiBlockInteractionHandler of both Digital Miners
=> Fix issue #690

src/me/mrCookieSlime/Slimefun/AncientAltar/RitualAnimation.java
Fixed issue #686 and added few sounds.
=> Fixed issue #686

src/me/mrCookieSlime/Slimefun/api/BlockStorage.java
This is a follow-up on [my comment here](https://github.com/TheBusyBiscuit/Slimefun4/issues/621#issuecomment-402007740)
This isn't really a 100% fix, but it seems to have made a difference. I figured it was at least worth giving other people the chance to test it out.
=> Hopefully reduce input node breakage

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/EnhancedFurnace.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
This in pair with a PR submitted to the CS-CoreLib repo will fix the Sawmill bug.
=> Fixed Sawmill Bug + Furnace Bug

README.md, src/me/mrCookieSlime/Slimefun/WorldEdit/WESlimefunManager.java, src/me/mrCookieSlime/Slimefun/listeners/AncientAltarListener.java
WorldEdit 7.0 fix
I tested it, and it works perfectly on latest spigot & worldedit :)
But this will broke support to older worldedit versions.
=> WorldEdit 7.0 support, Ancient Altar fix.

src/me/mrCookieSlime/Slimefun/Commands/SlimefunCommand.java, src/me/mrCookieSlime/Slimefun/Commands/SlimefunTabCompleter.java
& Replaced deprecated method in SlimefunCommand
___
Seems like CS-CoreLib Maven setup should be fixed first to prevent another build failure.
=> Added a missing tab complete

src/me/mrCookieSlime/Slimefun/WorldEdit/WESlimefunManager.java
Tested with WorldEdit 7 BETA 5 (currently the latest one).
Didn't try with FAWE though.
=> Updated WorldEdit API

pom.xml, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
- Updated API version to latest.
- Replaced deprecated method.
- Replaced old repo.
=> Updated CoreProtect API

src/me/mrCookieSlime/Slimefun/SlimefunStartup.java
& Replaced deprecated code in the same class.
=> Implement createDir() method

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/Talisman.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/ADrill.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AReactor.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutoAnvil.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutoDisenchanter.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AutoEnchanter.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CropGrowthAccelerator.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricDustWasher.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricGoldPan.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricSmeltery.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/OilPump.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/Refinery.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunManager.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/api/TickerTask.java, src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java
Optimized error logging in the first commit.
Evething else is related to deprecated code.
=> Replaced deprecated code

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Similiar to https://github.com/VoidAngel/Slimefun4/commit/2ae249dec4af999d3093ce88783c0912caa8ef4b
Fixes issue #870 - please see that issue for more information
=> Fix Soulbound Axe duplication bug

src/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Also fixes case when item disappear instead of being dropped of the inventory when closing it.
=> Prevent "Asynchronous entity add!"

src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java, src/me/mrCookieSlime/Slimefun/Android/ScriptPart.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
- Fixes #885.
- Added "Back" buttons in script menus, so you can easily move through them.
=> Better Androids

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Converts the inequality from `<` to `<=`
This is to change the range of the miners from 8x8 and 12x12 to the correct 9x9 and 13x13.
=> Fix miners not having the correct range

.gitignore, pom.xml, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunStartup.java
Update to MC 1.14
Do not merge until https://github.com/TheBusyBiscuit/CS-CoreLib/pull/75 is merged, I need to update the CS-CoreLib dependency
=> SF 4.1.17 - MC v1.14

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
=> Fix for #913

src/me/mrCookieSlime/Slimefun/Hashing/ItemHash.java
fixes "unclosed character literal" error some people may get on compile.
=>  unclosed character literal

src/me/mrCookieSlime/Slimefun/api/item_transport/CargoNet.java
This edit is for issue #879 . Tested on latest versions of Slimefun, ChestTerminal, and CS-CoreLib. 1.13 is to be determined.
=> Fix for issue #879

src/me/mrCookieSlime/Slimefun/CSCoreLibSetup/CSCoreLibLoader.java
Code from QuickSell:
https://github.com/TheBusyBiscuit/QuickSell/blob/master/src/me/mrCookieSlime/QuickSell/CSCoreLibSetup/CSCoreLibLoader.java
=> Replace SimpleJSON with Gson

pom.xml
* This allows the viewing of the sources from within an IDE when building against Slimefun.
=> Added maven source plugin

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Added in the new organic blocks as fuel for the Bio Reactor
=> Adding new 1.14 materials to BioReactor

src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/AdvancedCargoOutputNode.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/CargoInputNode.java
Trying again, should just be the two relevant files this time.
=> Fix issue #966 (Trying again)

src/me/mrCookieSlime/Slimefun/AncientAltar/RitualAnimation.java
Fix item swap exploit with AncientAltar Ritual
=> Fix Altar Item Swap Exploit

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
* Explosive Pickaxe will ignore liquid blocks (water, lava, etc)
* Smelter's Pickaxe will ignore Slimefun Blocks (fix duplication)
=> Some small fixes

src/me/mrCookieSlime/Slimefun/api/energy/EnergyNet.java
=> Fix energy regulators when exploded

src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java
=> Droid fix2

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
=> Fix broken spawner error

src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java
Friggin finally, stupid maven.
=> Fix busted spawners

pom.xml, src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
- Adding a new Tool called Explosive Shovel that breaks a 9x9x9 area of shovel blocks.
- Moving the Hologram Projector in Tech category a little bit upwards to make all multitools and jetboots in the same line and under/above their relevant items.(f.e lvl 1 jetboot, multitool and jetpack are now in the same column.)
=> Adding Explosive Shovel and beautifying Tech Category.

src/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
- Adding a new food called "Diet Cookie".
- Adding a recipe for Magic Workbench, containing of an elytra scale and a cookie.
- Levitates the player for 3 seconds.
- Adding a new research called "Diet Cookie" costing 3 levels.
=> Adding the Diet Cookie.

.github/PULL_REQUEST_TEMPLATE/features.md, .github/PULL_REQUEST_TEMPLATE/fix.md
Fixes the TODO items on the PR templates
=> Fix TODO items

src/me/mrCookieSlime/Slimefun/Setup/Messages.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java
I added a item-permission message to Messages and implemented it to the SlimefunGuide. I am not great at java so if you need to make it more efficient by all means, I don't quite know String Lists but it what I did does work within a limit.
Added item-permission into Messages class
Added item-permission getTranslation to SlimefunGuide
=> Added item-permission in messages

src/me/mrCookieSlime/Slimefun/GPS/Elevator.java, src/me/mrCookieSlime/Slimefun/GPS/GPSNetwork.java, src/me/mrCookieSlime/Slimefun/Objects/Research.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/StormStaff.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/MagicWorkbench.java, src/me/mrCookieSlime/Slimefun/Objects/tasks/JetBootsTask.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/me/mrCookieSlime/Slimefun/SlimefunGuide.java, src/me/mrCookieSlime/Slimefun/SlimefunPlugin.java, src/me/mrCookieSlime/Slimefun/androids/ProgrammableAndroid.java, src/me/mrCookieSlime/Slimefun/api/BlockStorage.java, src/me/mrCookieSlime/Slimefun/api/ErrorReport.java, src/me/mrCookieSlime/Slimefun/api/Slimefun.java, src/me/mrCookieSlime/Slimefun/api/SlimefunBackup.java, src/me/mrCookieSlime/Slimefun/api/TickerTask.java, src/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java, src/me/mrCookieSlime/Slimefun/commands/SlimefunCommand.java, src/me/mrCookieSlime/Slimefun/commands/SlimefunTabCompleter.java, src/me/mrCookieSlime/Slimefun/hooks/github/IntegerFormat.java, src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java
Just done some minor micro-optimisations
* Changed all single-char strings to char (unless it would be less beneficial)
* Removed useless String.valueOf's
* Used Loggers in-built formatter
* Save doing replace multiple times (especially replaceFirst which always compiles the regex)
N/A
=> Micro-optimisations

src/me/mrCookieSlime/Slimefun/listeners/FurnaceListener.java
Fixes the issue #1085.
- Made use of Math#min.
- Improved the fuel efficiency formula.
#1085
=> Fixes #1085.

src/config.yml
Some people disable auto-updates on dev builds because they can have issues. Let's instead advertise the stable branch
Adds a notice to the config
N/A
N/A
=> Add notice for stable

README.md
I have tweaked the text a bit, made it a bit more readable and removed/replaced unnecessary parts of text.
Edited the Discord part of the README.
Edited the top of the same file.
=> Tweaked the README a bit.

src/me/mrCookieSlime/Slimefun/GPS/TeleportationSequence.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/InfusedHopper.java, src/me/mrCookieSlime/Slimefun/Objects/tasks/MagnetTask.java, src/me/mrCookieSlime/Slimefun/ancient_altar/RitualAnimation.java, src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java
i changed the distance the sound will decay
i changed the following volume values
2 to 1 2x
1.7 to 1
5 to 1 3x
- [ x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
=> Changed values of sound decaying

src/me/mrCookieSlime/Slimefun/GPS/GPSNetwork.java, src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/me/mrCookieSlime/Slimefun/api/BlockInfoConfig.java, src/me/mrCookieSlime/Slimefun/api/BlockStorage.java, src/me/mrCookieSlime/Slimefun/api/TickerTask.java, src/me/mrCookieSlime/Slimefun/api/item_transport/CargoNet.java, src/me/mrCookieSlime/Slimefun/listeners/BackpackListener.java, src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java
A few performance improvements before I got distracted
Removing unneeded calls such as contains and containsKey
N/A
=> Some performance improvements

src/me/mrCookieSlime/Slimefun/Objects/tasks/ArmorTask.java, src/me/mrCookieSlime/Slimefun/Setup/SlimefunLocalization.java, src/me/mrCookieSlime/Slimefun/SlimefunPlugin.java, src/me/mrCookieSlime/Slimefun/api/HashedArmorpiece.java, src/me/mrCookieSlime/Slimefun/api/PlayerProfile.java
@WalshyDev plz reviw
+ Added HashedArmorpiece
+ Implemented caching for armorpieces to reduce SlimefunItem.getByItem() calls.
* Moved ArmorTask to its own Class
None
=> Improved Performance for Slimefun Armor

src/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java
Added lightning rune to the research.
Added lightning rune to the research.
because Cookie stated `I actually think that the Lightning Rune should get a seperate research.`
- [ x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
=> Added lightning rune to research and gave it its own research

src/me/mrCookieSlime/Slimefun/api/TickerTask.java, src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java
Order timings when needed by largest time. Also add in an average per machine.
Basically what I said in description
N/A
=> Order timings

.github/workflows/maven.yml
GitHub not smart.
Use a fork that fixes shit
https://github.com/actions/setup-java/issues/23
=> GitHub made dumb stuff

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/DietCookie.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/ExplosiveShovel.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/HerculesPickaxe.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/HunterTalisman.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/LumberAxe.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/MonsterJerky.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/PickaxeOfContainment.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/SmeltersPickaxe.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/SoulboundRune.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/SwordOfBeheading.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/gps/GPSTransmitter.java
fixed broken items
fixed broken items
Fixes #1187
=> fixed broken items

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/ExplosivePickaxe.java
Fixed explosive pickaxe forgot to add it in last pr
Fixed explosive pickaxe forgot to add it in last pr
Fixes  #1195
=> Fixed ExplosivePickaxe

src/main/java/me/mrCookieSlime/Slimefun/SlimefunGuide.java
Allow /sf cheat to have all categories unlocked
- If the player who who is using /sf cheat have not unlocked the category, they will still have access to it
- Removed empty code
None
=> Allow /sf cheat to have all categories unlocked

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/PickaxeOfVeinMining.java
fixes vein miner pickaxe
fixes vein miner pickaxe
fixes #1202
=> fixes #1202

src/main/java/me/mrCookieSlime/Slimefun/GPS/GPSNetwork.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/main/java/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java, src/main/java/me/mrCookieSlime/Slimefun/Setup/WikiSetup.java, src/main/java/me/mrCookieSlime/Slimefun/SlimefunPlugin.java, src/main/java/me/mrCookieSlime/Slimefun/api/SlimefunItemStack.java, src/main/java/me/mrCookieSlime/Slimefun/autosave/PlayerAutoSaver.java, src/main/java/me/mrCookieSlime/Slimefun/commands/subcommands/TeleporterCommand.java, src/main/java/me/mrCookieSlime/Slimefun/services/CustomItemDataService.java, src/main/java/me/mrCookieSlime/Slimefun/services/CustomTextureService.java, src/main/java/me/mrCookieSlime/Slimefun/services/MetricsService.java
Added support for 1.14's custom item models
Added CustomTextureService, created "services" package...
None
Naaaah
=> Added support for custom item models

src/main/java/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java
added jerkys to research + missing fertilizer and organic food
added jerkys to research + missing fertilizer and organic food
dont know why it showed that i touched line 3
=> added jerkys to research

src/main/java/me/mrCookieSlime/Slimefun/guides/GuideSettings.java
- Fixed color code not being parsed
- Removed empty lines
- Changed formatting according to the other pages in the guide
=> Minor changes to formatting

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/HandledBlock.java
It will be used in ExoticGarden.
Added a new constructor that allows using a new item system.
N/A
=> Added a new constructor for HandledBlock

src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
I kinda messed up my issue, sorry xD
But see #1281.
Check if the file exists before trying to delete it.
Resolves #1281.
=> Fixes #1281

src/main/java/me/mrCookieSlime/Slimefun/SlimefunPlugin.java, src/main/java/me/mrCookieSlime/Slimefun/guides/GuideSettings.java, src/main/java/me/mrCookieSlime/Slimefun/hooks/github/ContributionsConnector.java, src/main/java/me/mrCookieSlime/Slimefun/hooks/github/Contributor.java
Improved some code, blocked any name containing "bot" and added a way to have different GH and MC names so that people like myself and others actually aren't broken in the credits.
=> Allow for different GH and MC names + small improvements

src/main/java/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/main/java/me/mrCookieSlime/Slimefun/Setup/ResearchSetup.java, src/main/java/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java
Added the Soulbound trident
Added the Soulbound trident
=> Added Soulbound Trident

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/GrindStone.java
From https://discordapp.com/channels/565557184348422174/565569155848208404/65040601524600833
=> Grind andesite, granite, diorite to gravel

pom.xml, src/main/java/me/mrCookieSlime/Slimefun/SlimefunPlugin.java
1.15 barely changed anything so all we need to do is update this array and then the CS-CoreLib dep. So, once the PR above is merged I will push the dep change.
=> Support 1.15

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/OreCrusher.java
added a way to automate sand production
added gravel -> sand
N/A
=> added a way to automate sand production

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/ElectricPress.java
Changes are for the electric press.
Added recipes for iron and gold nuggets into their respective ingots. I also added a recipe for quartz into quartz blocks. 
https://discordapp.com/channels/565557184348422174/627048923122499584/652563773793763343
Same as above.
=> Added recipes

src/main/resources/wiki.json
Add wiki references for the entire Hazmat Suit, Armor Forge and Ore Crusher.
Quickly check if I made a typo but I don't think I did.
=> Add wiki references

src/main/resources/languages/messages_en.yml
New fortune cookie message
New fortune cookie message
N/A
=> New fortune cookie message

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/GrindStone.java
added prismarine to grind stone
added prismarine brick to grind stone
suggestion on discord https://canary.discordapp.com/channels/565557184348422174/627048923122499584/663109623288430643
prismarine to prismarine shards
prismarine brick to prismarine
N/A
=> Added prismarine to grindstone

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/generators/BioGenerator.java
Added string to BioGenerator
and changed 1 of the melons to melon slice 
Feature suggested on discord only didnt get approved since bot wasn't added
https://canary.discordapp.com/channels/565557184348422174/565569155848208404/652144863168430111
Added string to BioGenerator
changed melon to melon_slice
N/A
=> added string to BioGenerator

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/DebugFishListener.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/MagicSugar.java
Fixed Magic Sugar not able to be placed on Ancient Altars, and fixed Debug Fish on heads placed on walls.
Added an id check to MagicSugar.java and added a check if the head is a wall head and if so use Directional instead of Rotatable for DebugFishListener.java
Resolves #1379 
Resolves #1212
=> Small bug fixing

src/main/java/me/mrCookieSlime/Slimefun/api/item_transport/CargoManager.java, src/main/java/me/mrCookieSlime/Slimefun/api/item_transport/CargoNet.java
Added support for Furnaces and Brewing Stands to cargo nets. 
Added code to check the inventory to the insert and withdraw methods CargoManager.java (Intellij is still acting up and showing weird change files, all changes are at lines 47-68, 92-109, 148-197)
Resolves #114
=> Added support for furnaces and brewing stands to cargo nets.

src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
=> Sync up cache stuff in BlockStorage

src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/KnowledgeFlask.java
Give filled knowledge flask as SlimefunItem
=> Give filled knowledge flask as SlimefunItem

src/main/resources/languages/messages_pl.yml
=> Spelling correction

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AutonomousToolsListener.java
Fix #1513 by forbidding place hopper under block placer
Fix #1513 
Resolves #1513
=> Try to fix #1513

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/java/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java
Added Rainbow Concrete, Rainbow Concrete Powder, and Rainbow Glazed Terracotta
No changes to existing content
=> Add New Rainbow Blocks

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoEnchanter.java
=> Fixed #1613

src/main/resources/languages/recipes_hu.yml
Fixed recipes Hungarian translation
Removed unnecessary lines from recipes_hu.yml file.
=> Fixed recipes Hungarian translation

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Fix #1721 
Fix #1721
Fix #1721
=> Fixed #1721

src/main/java/me/mrCookieSlime/Slimefun/Objects/Research.java
Reverts TheBusyBiscuit/Slimefun4#1826
=> Revert "Easier to register items"

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/BackpackCommand.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/Commands.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/HiddenBackpack.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/RestoredBackpack.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/java/me/mrCookieSlime/Slimefun/Lists/SlimefunItems.java, src/main/resources/languages/messages_en.yml, src/main/resources/plugin.yml
Added a command that allows for backpack retrieval in the event they are lost. The command accepts a name and id, if those match up it spawns a Medium Backpack with the correct lore set in the sender's inventory - if not it sends them a message about which of the two isn't found.
Added a new SubCommand class, edited messages-en.yml to include 2 new error messages and and the command description, edited plugin.yml to add the command
N/A
- [ V ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ = ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
Only ExtraTools and TranscEndence were loaded with it, it does not mess with anything Addon related though.
- [ X …
=> Backpack command

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/CustomItemDataService.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/itemstack/ItemStackWrapper.java
allow null meta for the itemstackwrapper, since hasitemmeta is checked everywhere first anyways, creating meta for every item that the cargo net checks is pretty expensive
- [x ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ x] I followed the existing code standards and didn't mess up the formatting.
- [ x] I did my best to add documentation to any public classes or methods I added.
=> allow null meta

src/main/resources/languages/messages_en.yml
a few more quotes for fortune cookies
Added a few quotes to fortune cookies to pull from
6 new lines of dialogue for Fortune cookies
None
=> Fortune cookies

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicPills.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/PlayerInteractEntityListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/handlers/EntityInteractHandler.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/handlers/ItemHandler.java, src/main/java/me/mrCookieSlime/Slimefun/SlimefunPlugin.java, src/main/resources/languages/researches_en.yml
Added Magic Pills which are used to cure zombie villagers.
Approved suggestion #178
Added a new magical gadget called "Magic Pills".
Added a new recipe for Magic Workbench.
Added a new listener for PlayerInteractAtEntityEvent.
Added a new handler for the listener mentioned above.
N/A
=> Added Magic Pills. The Edited Version

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoBrewer.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/resources/languages/researches_en.yml
Added the Auto Brewer from an old approved suggestion of TheBusyBiscuit.
A new electric machine and corresponding research.
N/A
=> Auto brewer

CHANGELOG.md, README.md, pom.xml, src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/SlimefunGuideSettings.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/ChestSlimefunGuide.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/ChestMenuUtils.java, src/main/java/me/mrCookieSlime/Slimefun/SlimefunPlugin.java, src/main/resources/languages/recipes_en.yml, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/geo/TestResourceRegistration.java
This is a continuation (or postfix) of #2030 
* Ore Crusher now allows Nether Gold Ore
* Slimefun Guide now shows Smithing table recipes too
* Fixed a lot of color codes
=> Added 1.16 support

CHANGELOG.md, src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/GPSNetwork.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/TeleportationManager.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/Rechargeable.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/RechargeableHelper.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/CustomItemDataService.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/JetBoots.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/Jetpack.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/MultiTool.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/SolarHelmet.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/SolarGenerator.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoBrewer.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ChargingBench.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GadgetsListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/JetBootsTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/JetpackTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/SlimefunStartupTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/ChargableItem.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java, src/main/java/me/mrCookieSlime/Slimefun/api/energy/ItemEnergy.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestCategories.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestRechargeableItems.java
Item Energy uses lore to store energy which is really not good.
So I switched over to Persistent Data and updated all associated classes using this old system to use the new.
Next step would be to add Unit Tests for this.
@WalshyDev requesting your review.
* Item Energy uses Persistent Data now
* Added a proper "Rechargeable" interface which can be added to items to safely define what is chargeable and what isn't
* Fixed the long-time going on typo of "Chargable" with this
* Fully deprecated the classes ChargableItem and ItemEnergy now.
=> Lots of refactoring and rewriting of Item Energy

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosivePickaxe.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveShovel.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
Minor refactor to Explosive Tool/Pickaxe/Shovel.
Added some little documentations
Listed above.
N/A
=> Minor Refactor and Document Addition to Explosive classes.

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/BasicCircuitBoard.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MobDropListener.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/interfaces/ChanceDrop.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/interfaces/RandomMobDrop.java
This was in reference to pull request #980 I finally got around to making the requested changes
Added interface for ChanceDrop items
Added a check for chance drop items in the EntityDeathListener
Adjusted the basic circuit board from 100% chance down to 75%
#980
=> Added Chance Drop for MOB_DROP recipe items. References #980

src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ResearchUnlockEvent.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/Waypoint.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/network/Network.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/RechargeableHelper.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ChestTerminalNetwork.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/researching/Research.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubService.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/RecipeChoiceTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/BlockPlacer.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/CargoManager.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/MeatJerky.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/PortableGEOScanner.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/BackpackCrafter.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/PlayerProfileListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/PatternUtils.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/MachineRecipe.java, src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset.java, src/main/java/me/mrCookieSlime/Slimefun/api/inventory/DirtyChestMenu.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestBackpackListener.java
Title and also fixed a type. NUMBER_SEPERATOR -> NUMBER_SEPARATOR.
* Fix some useless escapes in regex
* Change the `,|\\.` to a simple `[,.]`
* Fixed typo
* Added some finals
* Changed `if (isPresent) execute()` to a simple `ifPresent(execute())`
N/A
=> Fix some regex, finals and replace isPresent with ifPresent

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
Added recipes (crush compressed carbon into carbon and carbon into coal) to the ore crusher as requested by approved suggestion #234.
Added the two recipes specified into the ore crusher.
N/A
=> Add recipes to crush compressed carbon into carbon and carbon into coal

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java, src/main/resources/config.yml
This will make backwards-compatibility mode disabled for new servers. (approved suggestion # 281 made by Walshy the king)
See description.
N/A
=> Backwards-compatibility mode disabled on new servers

src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/PiglinBarterDrop.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/RandomMobDrop.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/PiglinListener.java, src/main/java/me/mrCookieSlime/Slimefun/Lists/RecipeType.java
Added a new recipe type for piglin bartering
New Recipe type BARTER_DROP
updated RandomMobDrop type documentation
updated piglinlistener
updated slimefunregistry
N/A
=> Piglin drops fgithub

.github/CODE_OF_CONDUCT.md
This Pull Request adds a Code of Conduct to this repository.
I stuck to the widely used "Contributor Covenant Code of Conduct" but made large modifications to it.
I think this helps us communicate the way we want the community to behave and moderated and it is definitely a good thing to have.
@WalshyDev please review.
=> Added a Code of Conduct

.github/CONTRIBUTING.md
I also rewrote the CONTRIBUTING.md file now.
@WalshyDev Tell me what you think, whether I missed anything or whether something should be changed or added.
=> Rewritten CONTRIBUTING.md

src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/TeleportationManager.java
Fixed an issue when teleporters stopped working when the event is cancelled.
I changed it so the user will be removed from the teleportedUsers even if the event is cancelled.
=> Fixed teleporters not functioning if the teleport event is cancelled

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PickaxeOfVeinMining.java
Added a check for silk touch to Pickaxe of Vein Mining.
Fixes #2296 
Note: The changes aren't tested and were made on a mobile phone.
=> Possibly fixes #2296.

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ChestTerminalNetwork.java
Title says it all. Please don't [CI Skip] this.
Title says it all.
N/A
=> Edited markDirty() to clean connectorCache

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/InfusedHopper.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/MagnetTask.java
Changed the used sound categories in MagnetTask and InfusedHopper.
Changed the used sound categories in MagnetTask and InfusedHopper.
N/A
=> Changed the used sound categories.

.github/workflows/closed-issues-reason.yml, CHANGELOG.md, README.md, src/main/java/io/github/thebusybiscuit/slimefun4/api/geo/ResourceManager.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/TeleportationManager.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/package-info.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/package-info.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ChestTerminalNetwork.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/package-info.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/researching/Research.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/AutoSavingService.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/BlockDataService.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/VanillaItem.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/EnchantmentRune.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreWasher.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ButcherAndroidListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/DebugFishListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VillagerTradingListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/UraniumResource.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/SlimefunStartupTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/FireworkUtils.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/itemstack/ItemStackWrapper.java, src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSlimefunGuideListener.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestVanillaMachinesListener.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestVillagerTradingListener.java
I was bored so I fixed a BUNCH of typos. (My favourite was "classs" btw)
Should be CI skipped
Fixed a bunch of typos
N/A
=> Fixed some typos

.github/ISSUE_TEMPLATE/hacktoberfest-issue.md
We normally only use the Issues Tracker for bug reports. But as Hacktoberfest approaches, I think we should create some labelled issues which feature implementation gaps, some approved suggestions, bugs or refactoring plans that we wanna share with the Open-Source community.
These issues should only be opened by us, organization members, if someone wants to give another idea, they should go the usual suggestions-route on discord.
I want these issues to be as helpful and beginner-friendly as possible, here is my proposed solution.<br>
Feel free to give suggestions on what to add etc...
<hr>
This Issue is part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) - A yearly event which encourages participation in the open-source community. [Sign up on their …
=> Proposing a Hacktoberfest Issue template

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/MedicalSupply.java
we removed blindness effect instead of bad omen
changed blindness to bad omen
N/A
=> fixed issue

src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlock.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/TestUtilities.java
Made smeltery also accept blue fire.
Added a new supported tag, Tag.FIRE.
Fixes #2320
=> Fixing #2320

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/resources/languages/researches_en.yml
Added the energized energy capacitor from an approved Discord suggestion. Note: **NOT TESTED**
Added energized energy capacitor.
N/A
=> Added Energized Capacitor (From Discord suggestion)

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/CoalGenerator.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/TestUtilities.java
Tags
please dont break it this time <3
added materials to coalgen
=> Added materials to CoalGenerator

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/AbstractCargoNode.java
Changed channel to newChannel.
Fixes #2353
=> Possibly fixed #2353

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Made Necrotic Skull unplaceable.
- Made Necrotic Skull unplaceable
Fixes #2358
=> Made Necrotic Skull unplaceable

CONTRIBUTING.md
I am proposing some changes to the `CONTRIBUTING.md`.
Currently my advice has always been "stick to the current style".
But due to the ongoing increase in contributions, it may be wise to facilitate some concrete dos and don'ts.
Anything you wanna change or add?
=> Added some code-style guidelines to CONTRIBUTING

src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/ContributorsMenu.java
fixed empty slot in contributors
added slot 53 to draw background
idk
=> fix empty slot in contributors

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/BackpackCrafter.java
#2469 Crafted Elytra Cap in ArmorForge
https://streamable.com/p28b4f
Made `ArmorForge` extend `BackpackCrafter` instead of `MultiBlockMachine`
Used `EnchancedCraftingTable.java` as Reference to make further changes
Resolves #2469
=> Fixes ArmorForge

CHANGELOG.md, pom.xml, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/plugins/ThirdPartyPluginService.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/AdvancedFarmerAndroid.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/AbstractCargoNode.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/integrations/ClearLagIntegration.java, src/main/java/io/github/thebusybiscuit/slimefun4/integrations/IntegrationsManager.java, src/main/java/io/github/thebusybiscuit/slimefun4/integrations/McMMOIntegration.java, src/main/java/io/github/thebusybiscuit/slimefun4/integrations/PlaceholderAPIIntegration.java, src/main/java/io/github/thebusybiscuit/slimefun4/integrations/WorldEditIntegration.java, src/main/java/io/github/thebusybiscuit/slimefun4/integrations/package-info.java, src/main/resources/plugin.yml
The existing `ThirdPartyPluginService` was messy at best.
This PR refactors this and moves them from the `core/services/plugins` package into a dedicated `integrations` package which is more logical location if you are looking for these.
I also fixed a few issues and added ItemsAdder support (see https://github.com/LoneDev6/ItemsAdder-API).
* Refactored `ThirdPartyPluginService` into the `IntegrationsManager` class
* Moved all integrations into an `integrations` package
* Fixed #2575
* Added ItemsAdder compatibility
* Resolves #2575
=> Refactored integrations (+ Fixed #2575)

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Quick, temporary fix for #2636. I try fixing it better when I will have more time.## Changes
Items won't drop from ghost blocks (for now)
Resolves #2636
=> Temporary fix for #2636

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java
Add some more checks in order to make this more valid. This will resolve a lot of conflicts with other plugins. This has been confirmed fix with Citizens
Check #isCollidable and #hasGravity
Resolves #2647
=> Fixes #2647

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/plugins/ThirdPartyPluginService.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
This will disable the plugin in any environment named "CraftBukkit" which is not Spigot or Paper (or a fork of those).
We no longer support CB and this PR enforces this requirement to prevent things like... https://paste.walshy.dev/uhafukipec
=> Enforce Server Software requirements

pom.xml, src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
I changed the /sf version command to show a little more info
https://i.imgur.com/hENZ5nk.png
Changed ReflectionUtils.getVersion() to
Bukkit.getVersion()
N/A
=> Changed VersionsCommand to give more info

.github/workflows/pr-labels.yml
Made this action forever ago, was meant to add it in Hacktoberfest but... yeah.
Anyway, this adds labels to PRs based on the branch prefix. This is good for categorisation and helpful for people like myself for which PRs to look at first. We should add more labels but I thought these were some basic starting ones.
* new workflow file to add labels
N/A
=> Added PR labels

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/Translators.java, src/main/resources/languages/categories_cs.yml, src/main/resources/languages/recipes_cs.yml, src/main/resources/languages/researches_cs.yml
=> Updated czech translations

src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/SubCategory.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
=> Did walshys requested changes on multi category pr

src/main/java/io/github/thebusybiscuit/slimefun4/api/blocks/AbstractDataObject.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/blocks/EmptyBlockData.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/blocks/SlimefunBlockData.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/blocks/SlimefunWorldData.java
Minor improvements and api additions to the new blockstorage classes.
None of the changes are "tested" since the branch is WIP but there shouldn't
be anything which is broken. No javadocs were added for similar reasons as most
if not all additions are to undocumented WIP api. 
* Fixed unlocking the wrong lock in `AbstractDataObject`
* Add `AbstractDataObject#toJson(Gson)`
* Add `SlimefunDataObject#empty`
* Add `SlimefunWorldData#getBlockData(BlockPosition)`
=> Minor improvements to new block storage classes

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/AbstractAutoCrafter.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/SlimefunAutoCrafter.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/SlimefunItemRecipe.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaAutoCrafter.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaRecipe.java
Cleans up the small remarks regarding Cookie's autocrafters PR
- Add Validate.notNulls
- Whitelines
- Add missing access specifier to class
=> Follow up PR on AutoCrafters

src/main/resources/plugin.yml
I removed the part mentioning cscl in the `/sf` usage message. This is probably the smallest pr I ever did.
Removed a part mentioning CS-CoreLib from a message.
N/A
=> Fixed a Message

CHANGELOG.md, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java
Fixes issue #2914
Re-add fix which was reverted (see commit: https://github.com/Slimefun/Slimefun4/commit/7ba3a0b7fac696da98669621350b5d864980ed2a#diff-970c85b0bee57b1067490ca2d75d5ea2812e65c3691734e823ed41a7dda23204)
Resolves #2914
=> Fixes #2914

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java, src/main/resources/languages/messages_en.yml
Added a new message to multiblocks. This should help new players see that they havent placed a recipe inside of the block. This might help a little with the confusion people get about building the enhanced crafting table.
This is an example of a player getting confused with it.
Link goes to slimefun discord #questions.
https://canary.discord.com/channels/565557184348422174/565569972697301020/826188581495767110
New message to multiblocks
=> Added a new message to multiblocks to see if inventory is empty

CHANGELOG.md
Added missing changelog for #2756 
Added missing changelog for #2756
=> Added missing changelog for #2756

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNet.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
This commit introduces two optimizations to cargo handling. 
- Utilization of regex to validate integers in CargoNet#getFrequency,
- Smart shallow-cloning in CargoNetworkTask: using an ArrayList when round-robin is disabled
The commit used to test these optimizations can be found [here.](https://github.com/md5sha256/Slimefun4/commit/6d6e45f93193bee6e25f3dd52edbbc358f082680)
- Cargo System: Electric Smelter (Gold Ore --> Gold Ingot) connected to a chest. 
- 1x Input Node, 1x Output node
- Input node and Output node are whitelisted to accept Gold Ingots + 4 other random items
- Input node has round robin enabled
- Network visualisation is enabled
**Item Routing**
**Get Frequency**
Brief concluding notes: 
Whilst neither were tested using a proper benchmark such as JMH, the rough results do …
=> Optimizations to cargo

CHANGELOG.md, src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AutoDisenchantEvent.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AutoEnchantEvent.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
We had an AutoDisenchantEvent but not an AutoEnchantEvent :thonk:
Created AutoEnchantEvent to go along with AutoDisenchantEvent
N/A
---
https://user-images.githubusercontent.com/8492901/114275154-52444d80-9a19-11eb-861b-1046706dc018.mp4
=> AutoEnchantEvent

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
Add Quartz Block -> 4 Quartz to Grind Stone
P.S: I'm new to this so judge me. :)
<details>
<summary>Video in action:</summary>
https://user-images.githubusercontent.com/34732414/115135115-f6447f00-a03f-11eb-88b3-608daa3857bb.mp4
</details>
Add recipe to GrindStone class.
(Electric version automatically updated)
Discord Suggestion 746
=> Add Quartz Block -> 4 Quartz to Grind Stone (Suggestion-746)

CHANGELOG.md
=> Update changelog per #2911

.github/ISSUE_TEMPLATE/bug-report-beta.yaml
Mentioned existing issues, mentioned testing on dev if RC and mentioned Discord
=> Add a new header pointing to existing issues and Discord

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PickaxeOfTheSeeker.java, src/main/resources/languages/en/messages.yml
Pickaxe of The Seeker is missing error message when no ores were found
Moved locale path to follow current styling
Added Pickaxe of The Seeker error message when no ores were found
Fixes #3027
=> Update Pickaxe of The Seeker Localization

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
To fix strict order slot on Auto Disenchanter
Fix is stolen from #2982
Fixes #2978
https://youtu.be/akOvhaHzmzM
=> Fixes #2978

CHANGELOG.md, src/main/java/io/github/thebusybiscuit/slimefun4/core/services/holograms/HologramsService.java
This is a bit of a shot in the dark but maybe this fixes some of the hologram dupe glitches that some servers have experienced.
@Skizzles Could you perhaps test and verify this? It won't help with any existing glitched holograms of course. But it may mitigate the creation of these.
* Resolves #2927
=> Potentially fixed #2927

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/AbstractItemNetwork.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemFilter.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemStackAndInteger.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/itemstack/ItemStackWrapper.java, src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/utils/TestItemStackWrapper.java
Following some investigation in the SF discord after someone raised the question of CargoNet being slow, I have 
identified a few things: 
- The use of `ItemStackWrapper` is sometimes misused accidentally. (I.e creating an `ItemStackWrapper` of an `ItemStackWrapper`
- The `ItemStackWrapper` is not used efficiently (I.e creating multiple copies of the wrapper when performing `CargoNetTask#routeItems`: methods discard their own wrappers immediately after use instead of passing it on where plausible. 
This PR should not yet be merged; however, it can be reviewed. 
I am unsure how to proceed in benchmarking the proposed changes. There has been a ~ 9-10% performance improvement just from using `ItemStackWrapper#ofItem` instead of the constructor; however, this PR covers more changes than just …
=> Optimized use of ItemStackWrapper in the CargoNetworkTask

src/main/java/io/github/thebusybiscuit/slimefun4/api/ErrorReport.java
added time and date to the error report, this makes it easier for us to see when this error has been thrown. instead of just blindly trusted the user
Added time and date to the error report
N/A
=> added time and date to error report

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
See attached issue
Check for null, we do not need to check empty slots.
Resolves #3091
=> Fix IllegalArgumentException when ChestTerminal is requesting items

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoBrewer.java
See attached issues
Check whether potions can be upgraded/extended before actually doing so.
When fermenting, pass the old potion values instead of false.
Resolves #3093
Resolves #3095
=> AutoBrewer fixes

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
Added charcoal to coal recipe ass suggested by @Boomer-1 and approved on the SF discord
Added charcoal -> coal recipe to compressor
=> Add charcoal -> coal recipe

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
Hidden items are now not shown in the SlimefunGuide when using search
Add a check if item is hidden
Resolves #3105
=> Hidden items are now not shown in the SlimefunGuide when using search

.github/ISSUE_TEMPLATE/bug-report-beta.yaml
Updated the template to include 1.17
=> 1.17 exists now

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/IcyBow.java
Add a freeze effect on the Icy Bow
Added freeze effect on 1.17 to the icy bow
=> Add a freeze effect on the Icy Bow (1.17)

src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/ProduceCollector.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java
If an older Java version is found, tell them to update.
=> Encourage Java 16 on older versions

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
Add one recipe to grindstone (and electric ore grinder)
- Add diamond to 24 coal conversion
[Discord suggestion 774](https://discord.com/channels/565557184348422174/627048923122499584/822003610140409876)
=> Add diamond -> coal conversion

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/resources/languages/en/researches.yml
Add Trident Recipe
- Add trident recipe (4 tier 3 magic lumps, 4 water runes, 1 diamond sword)
[Discord suggestion 577](https://discord.com/channels/565557184348422174/627048923122499584/775973265763598336)
=> Add Trident recipe

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerThreadFactory.java
Shutdown the executor in TickerTask properly. Add nextThreadName to TickerTaskFactory
- Shutdown the `asyncExecutor` when finishing up.
- Add a numerical id to the `Thread` names in `TikcerTaskFactory`
=> Minor changes to the ticker task

.github/workflows/discord-webhook.yml, .github/workflows/maven-compiler.yml, .github/workflows/pr-labels.yml, .github/workflows/sonarcloud.yml, CHANGELOG.md, pom.xml, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java, src/main/resources/languages/en/researches.yml, src/main/resources/languages/fr/researches.yml, src/main/resources/languages/hu/researches.yml, src/main/resources/languages/zh-CN/researches.yml
=> Fix compile error in TickerTask

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/ContributionsConnector.java
Added my Minecraft name to the contributor list.
Added my Minecraft name to the contributor list.
=> Added My Minecraft Name to The Contributor List

src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java, src/main/resources/languages/messages_cs.yml
Fixes #2677 (all potions are treated as the same)
(Used #2831 as a basis)
Add potion meta check inside of SlimefunUtils#isItemSimilar()
Resolves #2677
=> Fixes #2677

src/main/java/io/github/thebusybiscuit/slimefun4/core/radiation/RadiationSymptom.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/RadioactivityListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/RadiationUtils.java
Applied requested changes from previous PR that were done after the merge
Apply the requested changes from the previous PR
#3131
=> Merge Semisol/Slimefun4@master into feature/armor-tasks

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
This PR updates the current message so it shows which category something needs to be unlocked in
discord suggestion #1477
=> Update message to show category

.github/workflows/maven-compiler.yml
@WalshyDev tried to in #3221 
Refer to #3221
Blob not being able to merge stuff
=> Run maven build workflows pt 2

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/FarmerAndroid.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
Androids can go past and do stuff outside the world border.
Added a checker if block location is outside world border, if true, return (or do not continue)
None
- [ / ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ / ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ / ] I followed the existing code standards and didn't mess up the formatting.
- [ / ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
=> WorldBorder Support

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricPress.java
Added some new 1.17 blocks to electric press
Added 4 "Amethyst Shard -> 1 Amethyst Block" recipe to Electric Press
Added 9 "Copper Ingot -> 1 Copper Block" recipe to Electric Press
Added 9 "Raw Iron -> 1 Raw Iron Block" recipe to Electric Press
Added 9 "Raw Gold -> 1 Raw Gold Block" recipe to Electric Press
Added 9 "Raw Copper -> 1 Raw Copper Block" recipe to Electric Press
=> Add some new 1.17 blocks to electric press

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
Implemented re-interruption when InterruptedException is thrown to keep the interrupted state.
Followed the code snipped in [Oracle JavaDocs](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html).
Re-Interruption of the Thread.
N/A(Sonarcloud bug)
=> Re-Interrupt the thread.

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectrifiedCrucible.java
This will make normal crucible and electrified crucible have the same recipe.
Add missing recipes to Electrified Crucible
Fixes #3273
=> Add missing recipes to Electrified Crucible

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java
You can bypass the item check by using off hand swap
Also idk where to add the comment on 'Fixes xxxx' thing
Added checks for off hand item
Fixes #3265
=> Fixes #3265

src/main/resources/tags/pressure_plates.json
Updated pressure plate tag
added crimson pressure plate and warped pressure plate to the pressure plate tag
n/a
=> updated pressure plate tag

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/AbstractResource.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java
BiomeMaps will become a big part of addons supporting 1.18+ and the current implementation doesn't make it easy or fun to implement. So, this PR will expand the API a bit in order to easily support third-party plugins/addons :)
Here is what you'd need to do, what you can do now and an even easier way:
```java
try {
// What you'd need to do :/
final BiomeMap<Integer> map = BiomeMap.fromJson(
new NamespacedKey(this, "test"),
String.join("", Files.readAllLines(new File(getClass().getResource("/biome-maps/test.json").getFile()).toPath())),
JsonElement::getAsInt
);
// now supported!
final BiomeMap<Integer> map1 = BiomeMap.fromResource(
new NamespacedKey(this, "test1"),
this,
"/biome-maps/test.json",
JsonElement::getAsInt
);
System.out.println(map1.getOrDefault(Biome.BADLANDS, 0)); …
```
=> Improved the API for BiomeMap

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
because this is likely an oversight
change the recipe output for easter apple pie from christmas apple pie to easter apple pie
easter apple pie is now obtainable
=> fix easter apple pie recipe output

.github/ISSUE_TEMPLATE/bug-report.yaml
Add 1.18.x version to bug report
Added 1.18.x version
Removed Yatopia and Tuinity since they have been discontinued for a while.
=> Add 1.18.x version to bug report

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/BioGenerator.java
Add fuel types to BioGenerator
Added Cocoa Beans, Beetroot, and Beetroot seeds as a fuel type in BioGenerator
Discord suggestion 1265
=> Add fuel types to BioGenerator

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/Freezer.java
Added transformation for ice that follows vanilla rules
a simple if statement that checks for the item setting
=> Added vanilla ratios to the freezer

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java, src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Check #3133 for details. Cargo would not check for CustomModelData so different ModelData items with the same name and lore would stack when sent via cargo, when they should not.
- Added an additional check for CustomModelData: this will help no matter the resource pack, and in particular will fix the issue with ItemsAdder.
Resolves #3133
=> Fixes #3133

pom.xml
Update Orebfuscator repo
Update their repo link, source [here](https://github.com/Imprex-Development/Orebfuscator)
=> Update Orebfuscator repo

src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java, src/main/java/io/github/thebusybiscuit/slimefun4/api/researches/Research.java
Added a way to get the name of a research without a required player/localization and some documentation to SlimefunItem
Added getUnlocalizedName to Research which just returns the name without localization
Added some documentation to SlimefunItem
None that i know of
=> unlocalized name and some docs

src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java, src/main/resources/config.yml
Makes guide search won't display item that its itemGroup not be unlocked by player
e.g. Seasonal Item
Makes guide search won't display item that its itemGroup not be unlocked by player
=> Improve guide search result

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java
Approved suggestion on discord that proposes to be able to fill empty bottles with water
- Adds support for empty glass bottles
Approved suggestion ```#1967```
=> Allow Fluid Pump to fill water bottles

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiddleClickListener.java
Fixes #3483 
Added null check
Resolves #3483
=> fixes #3483

src/main/java/io/github/thebusybiscuit/slimefun4/utils/ColoredMaterial.java
The shulker box has 16 color variants too, so it can be added to ColoredMaterial as well.
Add `SHULKER_BOX` to `ColoredMaterial` with 16 color variants of shulker box.
N/A
=> Add shulker box to ColoredMaterial

src/main/java/io/github/thebusybiscuit/slimefun4/utils/ColoredMaterial.java
Description:
The candle has 16 color variants, so it can be added to ColoredMaterial as well.
Proposed changes:
Add candle to ColoredMaterial with 16 color variants of candle.
Related Issues (if applicable)
N/A
=> Add candle to ColoredMaterial

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodComposter.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodFabricator.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Simple add of an item following player suggestion
Adding Seagrass organic food, crafted with the Food Fabricator
--- No Issues related ---
This is a speedly-made PR, I didn't searched that much where this add could break so feel free to notice me 👌
Work as intended with "some" add-ons"
=> Added Seagrass recipe (suggestion #398 from Mr.Moules)

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
=> fixed typo in SlimefunItems.java

.github/PULL_REQUEST_TEMPLATE.md
Sometimes PRs can be created and merged which (unintentionally) break compatibility with different Minecraft versions, such as the addition of candles to an enum. This aims to serve as a reminder to consider if the changes can affect other Minecraft versions.
Add an entry into the pull request checklist about supporting multiple Minecraft versions.
=> Add ensure compatibility in pull request template

src/main/resources/tags/dirt_variants.json
to fix mud not working with explosive shovel
added mud to dirt variants 
Resolves #3597
=> Fixes mud not working with explosive shovel

src/main/resources/tags/glass_blocks.json
Someone reported a bug in #LiteXpansion channel that tinted glass cant be cut with the glass cutter
So i added Tinted glass to the glass blocks
There dont seem to be panes from tinted glass.
I was thinking would this fit more into the glass.json or is this the right location?
Added tinted glass to glass_blocks.json
N/A
=> added tinted glass

pom.xml, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BeeWingsListener.java
Fixed an issue of bee wings erroring on startup.
An user reported it on github
https://canary.discord.com/channels/565557184348422174/565569972697301020/955709125579374622
added a null check for the bee wings
https://paste.walshy.dev/8yYVQCkxYYZz
https://canary.discord.com/channels/565557184348422174/565569972697301020/955709125579374622
=> Fix bee wings erroring on startup

src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
Currently, round-robin can lead to an uneven distribution with filled chests or output nodes with filters. This is because while the index gets incremented, the actual output node is just the "next available" node. 
<details>
<summary>Example</summary>
<br>
```
X - invalid output node (filled chest or filter)
O - available output node
output node array:
XXXXXXXXOO
```
During the first 8 ticks, the round robin index would be on an X, and the next available output node would be chosen (the first O). Then the 9th tick outputs onto the first O directly, and the 10th tick outputs onto the second O. Then the round robin index rolls back over to 0 and puts 9 ticks worth of items into the first O again. In this case, the first O is heavily biased and gets much more items than the second O. This …
=> Improve Round-Robin Accuracy

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoDrier.java
This pr adds a way to dry mud into clay.
This is also a default minecraft feature.
added mud to clay in the drier
=> added a way to turn mud into clay

pom.xml, src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlock.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Added freezer 3 
Added freezer 3 
n/a
=> added freezer 3

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/BioGenerator.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java, src/main/resources/wiki.json
Adding usability to the Glow Berries which were added in the 1.17 update.
+ Added Glow Berry Juice as a result of using Glow Berries in the Juicer. (With the same stats as Sweet Berry Juice)
+ Added Glow Berries as a fuel in the Bio Reactor. (With the same stats as Sweet Berries).
+ Updated Wiki to include Glow Berry Juice.
=> Added Glow Berries Being Useful

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/BlockPlacer.java
BlockPlacer being able to place `disabled` items
In the `onBlockDispense` method, adds a simple check if the item is disabled or not.
=> [Fix] BlockPlacer placing disabled items

.github/workflows/maven-compiler.yml, CHANGELOG.md
=> Update changelog (Worse than Walshy's version)

CHANGELOG.md
RC 33 is now out, update CHANGELOG for RC 34
=> RC 34 is next up

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java
This pr removes 1.14 and 1.15 from readme, bug report form, pull request form and other comments.
Full credits to @variananora 
Forgot to make a different branch :notLikeThis:
updated readme, bug report form, pull request form and other comments.
=> remove 1.14 from comments and others

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
This pr added more use for Cobbled deepslate.
A way to change deepslate cobblestone into gravel and into sand
=> more use for cobbled deepslate

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/EnhancedFurnaceListener.java
This pull request fixes an error that happens because there is not a null check
Add a null check.
Resolves #3741
=> Fix smelting null items

pom.xml
Changed paper repo.
They changed the repo https://canary.discord.com/channels/289587909051416579/1077385604012179486/1080730104717643776
=> Change paper repo

src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/ContributionsConnector.java
Added st392 to ignored users.
Fixed st392's MC name
fixed following error being thrown
[11:24:26] [Craft Scheduler Thread - 2/ERROR]: Exception while requesting skin: https://api.mojang.com/users/profiles/minecraft/st392
[11:24:26] [Craft Scheduler Thread - 0/WARN]: [Slimefun] Attempted to refresh skin cache, got this response: ExecutionException: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/st392
=> fixed username not being found

pom.xml
Currently, Slimefun prints a warning when running `mvn test´:
This pull request fixes this.
Added SLF4J-simple to pom.xml with "test" scope
=> Added SLF4J-simple to fix warning during tests

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricDustWasher.java
Adds the Sand to Salt Recipe to fully automate Salt (Continuation of #3686 )
Abstracts a minor bit of code to avoid a ton of repeated lines
Adds the Sand to Salt Recipe
=> Fully Implement Suggesstion 242 (Continuation of #3686)

CHANGELOG.md, README.md
1.20 is stable, releasing new RC.
=> Prep for RC-34

src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/ExternallyInteractable.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/interactions/InteractionResult.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/interactions/ItemInteractionResult.java, src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/interactions/package-info.java
Something I am working on in other addons is the ability to trigger/interact with other SlimefunItems when placed in the world in a generic way, i.e. not relying on depending on each individual possible addon/specifying ID's to do so. 
The idea here is that addons can implement the Interface and, within the overridden method, complete whatever actions it would like to do when being interacted with and return a result object denoting a generic summary what happened as part of the interaction. 
Currently I have only included the success of the interaction and any possible items generated as part of said interaction (as this has been initially thought up for networks). If there are any ideas for other things to be added that would also be useful, I can whack that in as well.
=> Adding ExternallyInteractable

CHANGELOG.md, README.md
Updated the CHANGELOG with all the changes and fixed MC version in README.
=> Prepped for RC-35

src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AutoCrafterListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/DispenserListener.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/EnhancedFurnaceListener.java, src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
This PR should resolve all blocks not working if they are disalbed.
Continuation of #2968
Added canuse/isdisabledin checks on serveral items.
Fixes #2957 
Fixes #2958 
Fixes #2959 
Fixes #3011
Fixes #2954
=> Fix some of the reported blocks not working

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java, src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
I am adding blackstone recipes to complete the remaining machines that do not have an appropriate blackstone recipe.
Added recipes to Grindstone and Ore Crusher
=> Add blackstone recipes to Grindstone and Ore Crusher

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Simple addition of an approved suggestion's item, it uses 24k gold blocks instead of the vanilla gold blocks.
Adding Enchanted Golden Apple, crafted in the Enhanced Crafting Table (and normal workbench since it's a VanillaItem)
Not applicable
=> Add Enchanted Golden Apple recipe (suggestion #2147 from punished_Garett)

src/main/resources/config.yml
Every word in research titles was capitalized except this one.
capitalize Chosen
N/A
=> capitalized Chosen

pom.xml
This PR updates dough.
Which has a fix in it that resolves the head issues in #4024 
this supercedes https://github.com/Slimefun/Slimefun4/pull/4026
Update Dough
Resolves #4024
=> fix heads showing as steve

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java, src/main/resources/config.yml
There was some discussion about people wanting to disable radiation.
Add a config option that controls whether the radiation task will be scheduled.
N/A
=> Add config option for radiation

src/main/resources/tags/block_placer_ignored_materials.json
Allow Slimefun to work on 1.20.3
make grass version dependent since they changed the material tag
https://www.spigotmc.org/threads/spigot-bungeecord-1-20-3.628172/
=> touch grass

CHANGELOG.md
Updated the changelog for RC-36, planned for tomorrow
N/A
N/A
=> Update changelog for RC-36

src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java
Fix a bug in `ArmorStandUtils`.
Only tested on 1.19.4 and 1.20.4.
Made version check logic correct.
=> fix: fix spawn in ArmorStandUtils

.github/workflows/release-candidates.yml
This PR changes the message in the releases to point towards blob.build instead of the old build page.
Point towards https://blob.build/project/Slimefun4/rc instead of the direct download on the old builds page
=> [ci skip] Update release candidates file

CHANGELOG.md
update the table of contents in changelog
update the table of contents in changelog
=> Fix ToC in CHANGELOG

pom.xml
PlotSquared module was updated in dough, this updates the pom to reflect that update.
Update dough to the latest version
N/A
=> Updated dough to latest

src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/RadiationTask.java
misjudgment of the attribute of radioactive items
=> fix: misjudgment of the attribute of radioactive items

src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Fix the problem with logging coordinates which might have commas in them. See also https://discord.com/channels/565557184348422174/624966637816381440/1278531359652057088
=> Fix message
